var dir_83efb4269fa89047a37e895c24f65331 =
[
    [ "abi.h", "abi_8h.html", "abi_8h" ],
    [ "gbi.h", "gbi_8h.html", "gbi_8h" ],
    [ "gs2dex.h", "gs2dex_8h.html", "gs2dex_8h" ],
    [ "gu.h", "gu_8h.html", "gu_8h" ],
    [ "libaudio.h", "libaudio_8h.html", "libaudio_8h" ],
    [ "libultra.h", "libultra_8h.html", "libultra_8h" ],
    [ "mbi.h", "mbi_8h.html", "mbi_8h" ],
    [ "os.h", "os_8h.html", "os_8h" ],
    [ "os_ai.h", "os__ai_8h.html", null ],
    [ "os_cache.h", "os__cache_8h.html", null ],
    [ "os_cont.h", "os__cont_8h.html", "os__cont_8h" ],
    [ "os_eeprom.h", "os__eeprom_8h.html", "os__eeprom_8h" ],
    [ "os_exception.h", "os__exception_8h.html", "os__exception_8h" ],
    [ "os_internal.h", "os__internal_8h.html", "os__internal_8h" ],
    [ "os_libc.h", "os__libc_8h.html", "os__libc_8h" ],
    [ "os_message.h", "os__message_8h.html", "os__message_8h" ],
    [ "os_misc.h", "os__misc_8h.html", "os__misc_8h" ],
    [ "os_pi.h", "os__pi_8h.html", "os__pi_8h" ],
    [ "os_rdp.h", "os__rdp_8h.html", null ],
    [ "os_thread.h", "os__thread_8h.html", "os__thread_8h" ],
    [ "os_time.h", "os__time_8h.html", "os__time_8h" ],
    [ "os_tlb.h", "os__tlb_8h.html", "os__tlb_8h" ],
    [ "os_vi.h", "os__vi_8h.html", "os__vi_8h" ],
    [ "R4300.h", "R4300_8h.html", "R4300_8h" ],
    [ "rcp.h", "rcp_8h.html", "rcp_8h" ],
    [ "sptask.h", "sptask_8h.html", "sptask_8h" ],
    [ "ucode.h", "ucode_8h.html", "ucode_8h" ],
    [ "ultratypes.h", "ultratypes_8h.html", "ultratypes_8h" ]
];