FROM ubuntu:22.04 as build

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        binutils-mips-linux-gnu \
        build-essential \
        libaudiofile-dev \
        libcapstone-dev \
        git \
        pkg-config \
        python3 \
	wget \
        zlib1g-dev

RUN TEMP_DEB="$(mktemp)" && \
    wget -O "$TEMP_DEB" 'https://github.com/n64decomp/qemu-irix/releases/download/v2.11-deb/qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb'  && \
    dpkg -i "$TEMP_DEB" && \
    rm -f "$TEMP_DEB"

RUN mkdir /opt/assets

COPY roms/ /opt/assets
