FROM ubuntu:22.04 as build

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        binutils-mips-linux-gnu \
        build-essential \
        libaudiofile-dev \
        libcapstone-dev \
        git \
        pkg-config \
        python3 \
	wget \
        zlib1g-dev

RUN mkdir /opt/assets

COPY roms/ /opt/assets
