# This file is auto-generated. DO NOT MODIFY!

SAFE_C_FILES :=    \
    build/us/src/camera.o    \
    build/us/src/spawn_players.o    \
    build/us/src/code_8003DC40.o    \
    build/us/src/code_80091440.o    \
    build/us/src/effects.o    \
    build/us/src/code_80057C60_var.o    \
    build/us/src/code_800029B0.o    \
    build/us/src/animation.o    \
    build/us/src/player_controller.o    \
    build/us/src/profiler.o    \
    build/us/src/render_player.o    \
    build/us/src/code_80086E70.o    \
    build/us/src/staff_ghosts.o    \
    build/us/src/gbiMacro.o    \
    build/us/src/kart_dma.o    \
    build/us/src/math_util_2.o    \
    build/us/src/main.o    \
    build/us/src/data/kart_attributes.o    \
    build/us/src/data/path_spawn_metadata.o    \
    build/us/src/data/textures.o    \
    build/us/src/data/trig_tables_bss.o    \
    build/us/src/data/data_segment2.o    \
    build/us/src/audio/seqplayer.o    \
    build/us/src/audio/heap.o    \
    build/us/src/audio/effects.o    \
    build/us/src/audio/playback.o    \
    build/us/src/audio/audio_session_presets.o    \
    build/us/src/audio/port_eu.o    \
    build/us/src/buffers/gfx_output_buffer.o    \
    build/us/src/buffers/trig_tables.o    \
    build/us/src/buffers/buffers.o    \
    build/us/src/buffers/random.o    \
    build/us/src/buffers/trig_tables_bss.o    \
    build/us/src/buffers/memory_pool.o    \
    build/us/src/ending/credits.o    \
    build/us/src/ending/code_80280000.o    \
    build/us/src/ending/ceremony_and_credits.o    \
    build/us/src/ending/dl_unk_80284EE0.o    \
    build/us/src/ending/code_80281780.o    \
    build/us/src/ending/podium_ceremony_actors.o    \
    build/us/src/ending/code_80281C40.o    \
    build/us/src/ending/camera_junk.o    \
    build/us/src/debug/debug.o    \
    build/us/src/debug/crash_screen_enhancement.o    \
    build/us/src/racing/collision.o    \
    build/us/src/racing/skybox_and_splitscreen.o    \
    build/us/src/racing/memory.o    \
    build/us/src/racing/race_logic.o    \
    build/us/src/racing/actors_extended.o    \
    build/us/src/racing/render_courses.o    \
    build/us/src/racing/actors.o    \
    build/us/src/os/guOrthoF.o    \
    build/us/src/os/guLookAtF.o    \
    build/us/src/os/__osSiDeviceBusy.o    \
    build/us/src/os/_Litob.o    \
    build/us/src/os/osContInit.o    \
    build/us/src/os/osInitialize.o    \
    build/us/src/os/osAiSetNextBuffer.o    \
    build/us/src/os/guMtxCatL.o    \
    build/us/src/os/__osAiDeviceBusy.o    \
    build/us/src/os/contramread.o    \
    build/us/src/os/osSpTaskLoadGo.o    \
    build/us/src/os/crc.o    \
    build/us/src/os/osCreateMesgQueue.o    \
    build/us/src/os/guRotateF.o    \
    build/us/src/os/__osLeoInterrupt.o    \
    build/us/src/os/osContStartReadData.o    \
    build/us/src/os/osGetThreadPri.o    \
    build/us/src/os/osPfsNumFiles.o    \
    build/us/src/os/__osSiRawReadIo.o    \
    build/us/src/os/osSpTaskYield.o    \
    build/us/src/os/osStartThread.o    \
    build/us/src/os/osViData.o    \
    build/us/src/os/osPfsFileState.o    \
    build/us/src/os/contpfs.o    \
    build/us/src/os/leointerrupt.o    \
    build/us/src/os/osPfsAllocateFile.o    \
    build/us/src/os/ldiv.o    \
    build/us/src/os/osSpTaskYielded.o    \
    build/us/src/os/__osSpSetPc.o    \
    build/us/src/os/osSetTime.o    \
    build/us/src/os/osYieldThread.o    \
    build/us/src/os/osPiRawStartDma.o    \
    build/us/src/os/osSetTimer.o    \
    build/us/src/os/osPfsDeleteFile.o    \
    build/us/src/os/__osSpDeviceBusy.o    \
    build/us/src/os/osEepromRead.o    \
    build/us/src/os/osPiRawReadIo.o    \
    build/us/src/os/osSetEventMesg.o    \
    build/us/src/os/NaN.o    \
    build/us/src/os/osJamMesg.o    \
    build/us/src/os/osPfsChecker.o    \
    build/us/src/os/sprintf.o    \
    build/us/src/os/_Printf.o    \
    build/us/src/os/osViTable.o    \
    build/us/src/os/osEepromLongWrite.o    \
    build/us/src/os/__osEPiRawWriteIo.o    \
    build/us/src/os/osViSetEvent.o    \
    build/us/src/os/__osGetCurrFaultedThread.o    \
    build/us/src/os/osCreatePiManager.o    \
    build/us/src/os/epidma.o    \
    build/us/src/os/osCartRomInit.o    \
    build/us/src/os/osPfsFreeBlocks.o    \
    build/us/src/os/osPfsSearchFile.o    \
    build/us/src/os/__osAtomicDec.o    \
    build/us/src/os/osViBlack.o    \
    build/us/src/os/__osViInit.o    \
    build/us/src/os/osEepromWrite.o    \
    build/us/src/os/osAiSetFrequency.o    \
    build/us/src/os/__osEPiRawReadIo.o    \
    build/us/src/os/guLookAtRef.o    \
    build/us/src/os/guPerspectiveF.o    \
    build/us/src/os/contramwrite.o    \
    build/us/src/os/osGetTime.o    \
    build/us/src/os/__osViSwapContext.o    \
    build/us/src/os/alBnkfNew.o    \
    build/us/src/os/__osSpSetStatus.o    \
    build/us/src/os/osPfsReadWriteFile.o    \
    build/us/src/os/osPiStartDma.o    \
    build/us/src/os/osRecvMesg.o    \
    build/us/src/os/osDestroyThread.o    \
    build/us/src/os/string.o    \
    build/us/src/os/__osSiRawWriteIo.o    \
    build/us/src/os/osPfsInit.o    \
    build/us/src/os/guMtxCatF.o    \
    build/us/src/os/osPfsIsPlug.o    \
    build/us/src/os/__osDequeueThread.o    \
    build/us/src/os/__osSiCreateAccessQueue.o    \
    build/us/src/os/osViSwapBuffer.o    \
    build/us/src/os/is_debug.o    \
    build/us/src/os/__osViGetCurrentContext.o    \
    build/us/src/os/__osPiCreateAccessQueue.o    \
    build/us/src/os/__osSpRawStartDma.o    \
    build/us/src/os/__osSyncPutChars.o    \
    build/us/src/os/osSendMesg.o    \
    build/us/src/os/osSyncPrintf.o    \
    build/us/src/os/__osResetGlobalIntMask.o    \
    build/us/src/os/guScaleF.o    \
    build/us/src/os/osSetThreadPri.o    \
    build/us/src/os/__osDevMgrMain.o    \
    build/us/src/os/osVirtualToPhysical.o    \
    build/us/src/os/osViSetMode.o    \
    build/us/src/os/__osSetHWIntrRoutine.o    \
    build/us/src/os/osCreateViManager.o    \
    build/us/src/os/__osSiRawStartDma.o    \
    build/us/src/os/guNormalize.o    \
    build/us/src/os/osLeoDiskInit.o    \
    build/us/src/os/__osSpGetStatus.o    \
    build/us/src/os/osEepromLongRead.o    \
    build/us/src/os/_Ldtob.o    \
    build/us/src/os/guMtxF2L.o    \
    build/us/src/os/osEPiRawStartDma.o    \
    build/us/src/os/osPiGetCmdQueue.o    \
    build/us/src/os/osAiGetLength.o    \
    build/us/src/os/osViSetSpecialFeatures.o    \
    build/us/src/os/osCreateThread.o    \
    build/us/src/os/osTimer.o    \
    build/us/src/os/osEepromProbe.o    \
    build/us/src/os/__osSetGlobalIntMask.o    \
    build/us/src/os/guTranslateF.o    \
    build/us/src/os/math/llconv.o    \
    build/us/src/os/math/cosf.o    \
    build/us/src/os/math/llmuldiv.o    \
    build/us/src/os/math/sinf.o    \