#ifndef MOO_MOO_FARM_COURSE_DATA_H
#define MOO_MOO_FARM_COURSE_DATA_H

#include <ultra64.h>
#include <PR/gbi.h>
#include <actor_types.h>
#include <waypoints.h>
#include <course.h>

extern Gfx d_course_moo_moo_farm_dl_0[];
extern Gfx d_course_moo_moo_farm_dl_30[];
extern Gfx d_course_moo_moo_farm_dl_48[];
extern Gfx d_course_moo_moo_farm_dl_60[];
extern Gfx d_course_moo_moo_farm_dl_78[];
extern Gfx d_course_moo_moo_farm_dl_88[];
extern Gfx d_course_moo_moo_farm_dl_338[];
extern Gfx d_course_moo_moo_farm_dl_598[];
extern Gfx d_course_moo_moo_farm_dl_8A0[];
extern Gfx d_course_moo_moo_farm_dl_B00[];
extern Gfx d_course_moo_moo_farm_dl_D70[];
extern Gfx d_course_moo_moo_farm_dl_FE0[];
extern Gfx d_course_moo_moo_farm_dl_12B8[];
extern Gfx d_course_moo_moo_farm_dl_1530[];
extern Gfx d_course_moo_moo_farm_dl_1790[];
extern Gfx d_course_moo_moo_farm_dl_1A20[];
extern Gfx d_course_moo_moo_farm_dl_1D00[];
extern Gfx d_course_moo_moo_farm_dl_1F58[];
extern Gfx d_course_moo_moo_farm_dl_2190[];
extern Gfx d_course_moo_moo_farm_dl_2470[];
extern Gfx d_course_moo_moo_farm_dl_27A8[];
extern Gfx d_course_moo_moo_farm_dl_2A10[];
extern Gfx d_course_moo_moo_farm_dl_2C38[];
extern Gfx d_course_moo_moo_farm_dl_2F20[];
extern Gfx d_course_moo_moo_farm_dl_3238[];
extern Gfx d_course_moo_moo_farm_dl_34A0[];
extern Gfx d_course_moo_moo_farm_dl_36B8[];
extern Gfx d_course_moo_moo_farm_dl_39F8[];
extern Gfx d_course_moo_moo_farm_dl_3CB0[];
extern Gfx d_course_moo_moo_farm_dl_3EB8[];
extern Gfx d_course_moo_moo_farm_dl_4098[];
extern Gfx d_course_moo_moo_farm_dl_4428[];
extern Gfx d_course_moo_moo_farm_dl_46D8[];
extern Gfx d_course_moo_moo_farm_dl_4910[];
extern Gfx d_course_moo_moo_farm_dl_4AD0[];
extern Gfx d_course_moo_moo_farm_dl_4E00[];
extern Gfx d_course_moo_moo_farm_dl_5040[];
extern Gfx d_course_moo_moo_farm_dl_5290[];
extern Gfx d_course_moo_moo_farm_dl_5458[];
extern Gfx d_course_moo_moo_farm_dl_5758[];
extern Gfx d_course_moo_moo_farm_dl_5990[];
extern Gfx d_course_moo_moo_farm_dl_5BF8[];
extern Gfx d_course_moo_moo_farm_dl_5DF0[];
extern Gfx d_course_moo_moo_farm_dl_60A8[];
extern Gfx d_course_moo_moo_farm_dl_62D0[];
extern Gfx d_course_moo_moo_farm_dl_6548[];
extern Gfx d_course_moo_moo_farm_dl_6778[];
extern Gfx d_course_moo_moo_farm_dl_6A70[];
extern Gfx d_course_moo_moo_farm_dl_6CB8[];
extern Gfx d_course_moo_moo_farm_dl_6FF0[];
extern Gfx d_course_moo_moo_farm_dl_7218[];
extern Gfx d_course_moo_moo_farm_dl_74C8[];
extern Gfx d_course_moo_moo_farm_dl_7718[];
extern Gfx d_course_moo_moo_farm_dl_7A80[];
extern Gfx d_course_moo_moo_farm_dl_7CD8[];
extern Gfx d_course_moo_moo_farm_dl_7F78[];
extern Gfx d_course_moo_moo_farm_dl_81E8[];
extern Gfx d_course_moo_moo_farm_dl_84D0[];
extern Gfx d_course_moo_moo_farm_dl_8728[];
extern Gfx d_course_moo_moo_farm_dl_89A0[];
extern Gfx d_course_moo_moo_farm_dl_8C00[];
extern Gfx d_course_moo_moo_farm_dl_8F18[];
extern Gfx d_course_moo_moo_farm_dl_9178[];
extern Gfx d_course_moo_moo_farm_dl_93D0[];
extern Gfx d_course_moo_moo_farm_dl_9640[];
extern Gfx d_course_moo_moo_farm_dl_9938[];
extern Gfx d_course_moo_moo_farm_dl_9BB0[];
extern Gfx d_course_moo_moo_farm_dl_9DF8[];
extern Gfx d_course_moo_moo_farm_dl_A010[];
extern Gfx d_course_moo_moo_farm_dl_A2C0[];
extern Gfx d_course_moo_moo_farm_dl_A568[];
extern Gfx d_course_moo_moo_farm_dl_A7B0[];
extern Gfx d_course_moo_moo_farm_dl_A9C8[];
extern Gfx d_course_moo_moo_farm_dl_ACB0[];
extern Gfx d_course_moo_moo_farm_dl_B020[];
extern Gfx d_course_moo_moo_farm_dl_B230[];
extern Gfx d_course_moo_moo_farm_dl_B478[];
extern Gfx d_course_moo_moo_farm_dl_B798[];
extern Gfx d_course_moo_moo_farm_dl_BB00[];
extern Gfx d_course_moo_moo_farm_dl_BCE8[];
extern Gfx d_course_moo_moo_farm_dl_BF10[];
extern Gfx d_course_moo_moo_farm_dl_C180[];
extern Gfx d_course_moo_moo_farm_dl_C4F8[];
extern Gfx d_course_moo_moo_farm_dl_C6D8[];
extern Gfx d_course_moo_moo_farm_dl_C950[];
extern Gfx d_course_moo_moo_farm_dl_CBC8[];
extern Gfx d_course_moo_moo_farm_dl_CF58[];
extern Gfx d_course_moo_moo_farm_dl_D140[];
extern Gfx d_course_moo_moo_farm_dl_D408[];
extern Gfx d_course_moo_moo_farm_dl_D6B0[];
extern Gfx d_course_moo_moo_farm_dl_DA50[];
extern Gfx d_course_moo_moo_farm_dl_DC70[];
extern Gfx d_course_moo_moo_farm_dl_DF60[];
extern Gfx d_course_moo_moo_farm_dl_E1D8[];
extern Gfx d_course_moo_moo_farm_dl_E4B0[];
extern Gfx d_course_moo_moo_farm_dl_E708[];
extern Gfx d_course_moo_moo_farm_dl_EA18[];
extern struct TrackWayPoint d_course_moo_moo_farm_unknown_waypoints[];
extern struct TrackWayPoint d_course_moo_moo_farm_track_waypoints[];
extern u8 d_course_moo_moo_farm_mole_tlut[];
extern u8 d_course_moo_moo_farm_mole_frames[][2048];
extern u8 d_course_moo_moo_farm_mole_dirt[];
extern u8 d_course_moo_moo_farm_cow_tlut[];
extern Vtx d_course_moo_moo_farm_cow_model[];
extern Vtx d_course_moo_moo_farm_unknown_model1[];
extern Vtx d_course_moo_moo_farm_unknown_model2[];
extern Gfx d_course_moo_moo_farm_dl_13B88[];
extern Gfx d_course_moo_moo_farm_dl_cow1[];
extern Gfx d_course_moo_moo_farm_dl_cow2[];
extern Gfx d_course_moo_moo_farm_dl_cow3[];
extern Gfx d_course_moo_moo_farm_dl_cow4[];
extern Gfx d_course_moo_moo_farm_dl_cow5[];
extern Vtx d_course_moo_moo_farm_tree_model[];
extern Gfx d_course_moo_moo_farm_dl_tree[];
extern Gfx d_course_moo_moo_farm_dl_13FF8[];
extern Gfx d_course_moo_moo_farm_dl_14060[];
extern Gfx d_course_moo_moo_farm_dl_14088[];
extern struct ActorSpawnData d_course_moo_moo_farm_cow_spawn[];
extern struct ActorSpawnData d_course_moo_moo_farm_tree_spawn[];
extern struct ActorSpawnData d_course_moo_moo_farm_item_box_spawns[];
extern TrackSections d_course_moo_moo_farm_addr[];

#endif
