# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.section .data

.ifdef VERSION_JP
.incbin "bin/audiotables.jp.v11.bin" # JP sample bank (0x190 larger)
.else
.incbin "bin/audiotables.bin" # Audiotables and data
.endif

