#ifndef BOWSERS_CASTLE_COURSE_DATA_H
#define BOWSERS_CASTLE_COURSE_DATA_H

#include <ultra64.h>
#include <PR/gbi.h>
#include <actor_types.h>
#include <waypoints.h>
#include <course.h>

extern Gfx d_course_bowsers_castle_dl_0[];
extern Gfx d_course_bowsers_castle_dl_110[];
extern Gfx d_course_bowsers_castle_dl_230[];
extern Gfx d_course_bowsers_castle_dl_398[];
extern Gfx d_course_bowsers_castle_dl_428[];
extern Gfx d_course_bowsers_castle_dl_4F0[];
extern Gfx d_course_bowsers_castle_dl_640[];
extern Gfx d_course_bowsers_castle_dl_7A0[];
extern Gfx d_course_bowsers_castle_dl_860[];
extern Gfx d_course_bowsers_castle_dl_8E8[];
extern Gfx d_course_bowsers_castle_dl_9F8[];
extern Gfx d_course_bowsers_castle_dl_AE0[];
extern Gfx d_course_bowsers_castle_dl_B88[];
extern Gfx d_course_bowsers_castle_dl_C08[];
extern Gfx d_course_bowsers_castle_dl_D20[];
extern Gfx d_course_bowsers_castle_dl_E00[];
extern Gfx d_course_bowsers_castle_dl_EA8[];
extern Gfx d_course_bowsers_castle_dl_F08[];
extern Gfx d_course_bowsers_castle_dl_1040[];
extern Gfx d_course_bowsers_castle_dl_1138[];
extern Gfx d_course_bowsers_castle_dl_11F0[];
extern Gfx d_course_bowsers_castle_dl_1248[];
extern Gfx d_course_bowsers_castle_dl_1290[];
extern Gfx d_course_bowsers_castle_dl_12D0[];
extern Gfx d_course_bowsers_castle_dl_1330[];
extern Gfx d_course_bowsers_castle_dl_1350[];
extern Gfx d_course_bowsers_castle_dl_1370[];
extern Gfx d_course_bowsers_castle_dl_13A0[];
extern Gfx d_course_bowsers_castle_dl_13C0[];
extern Gfx d_course_bowsers_castle_dl_13E0[];
extern Gfx d_course_bowsers_castle_dl_1448[];
extern Gfx d_course_bowsers_castle_dl_1488[];
extern Gfx d_course_bowsers_castle_dl_14B0[];
extern Gfx d_course_bowsers_castle_dl_1520[];
extern Gfx d_course_bowsers_castle_dl_1590[];
extern Gfx d_course_bowsers_castle_dl_1608[];
extern Gfx d_course_bowsers_castle_dl_1690[];
extern Gfx d_course_bowsers_castle_dl_1710[];
extern Gfx d_course_bowsers_castle_dl_1788[];
extern Gfx d_course_bowsers_castle_dl_17D0[];
extern Gfx d_course_bowsers_castle_dl_1818[];
extern Gfx d_course_bowsers_castle_dl_1860[];
extern Gfx d_course_bowsers_castle_dl_18C0[];
extern Gfx d_course_bowsers_castle_dl_1928[];
extern Gfx d_course_bowsers_castle_dl_1960[];
extern Gfx d_course_bowsers_castle_dl_19A8[];
extern Gfx d_course_bowsers_castle_dl_19F8[];
extern Gfx d_course_bowsers_castle_dl_1A40[];
extern Gfx d_course_bowsers_castle_dl_1A90[];
extern Gfx d_course_bowsers_castle_dl_1AD8[];
extern Gfx d_course_bowsers_castle_dl_1B10[];
extern Gfx d_course_bowsers_castle_dl_1B58[];
extern Gfx d_course_bowsers_castle_dl_1BB0[];
extern Gfx d_course_bowsers_castle_dl_1C10[];
extern Gfx d_course_bowsers_castle_dl_1C38[];
extern Gfx d_course_bowsers_castle_dl_1C60[];
extern Gfx d_course_bowsers_castle_dl_1C98[];
extern Gfx d_course_bowsers_castle_dl_1CD0[];
extern Gfx d_course_bowsers_castle_dl_1DF8[];
extern Gfx d_course_bowsers_castle_dl_1EB0[];
extern Gfx d_course_bowsers_castle_dl_1FA0[];
extern Gfx d_course_bowsers_castle_dl_2008[];
extern Gfx d_course_bowsers_castle_dl_2130[];
extern Gfx d_course_bowsers_castle_dl_21F0[];
extern Gfx d_course_bowsers_castle_dl_22E8[];
extern Gfx d_course_bowsers_castle_dl_2398[];
extern Gfx d_course_bowsers_castle_dl_24B8[];
extern Gfx d_course_bowsers_castle_dl_2578[];
extern Gfx d_course_bowsers_castle_dl_2688[];
extern Gfx d_course_bowsers_castle_dl_2760[];
extern Gfx d_course_bowsers_castle_dl_2880[];
extern Gfx d_course_bowsers_castle_dl_2958[];
extern Gfx d_course_bowsers_castle_dl_2A60[];
extern Gfx d_course_bowsers_castle_dl_2B80[];
extern Gfx d_course_bowsers_castle_dl_2C48[];
extern Gfx d_course_bowsers_castle_dl_2D08[];
extern Gfx d_course_bowsers_castle_dl_2DF8[];
extern Gfx d_course_bowsers_castle_dl_2F30[];
extern Gfx d_course_bowsers_castle_dl_2FB0[];
extern Gfx d_course_bowsers_castle_dl_3050[];
extern Gfx d_course_bowsers_castle_dl_3158[];
extern Gfx d_course_bowsers_castle_dl_3230[];
extern Gfx d_course_bowsers_castle_dl_32C0[];
extern Gfx d_course_bowsers_castle_dl_3338[];
extern Gfx d_course_bowsers_castle_dl_3480[];
extern Gfx d_course_bowsers_castle_dl_3508[];
extern Gfx d_course_bowsers_castle_dl_35D0[];
extern Gfx d_course_bowsers_castle_dl_3678[];
extern Gfx d_course_bowsers_castle_dl_37D8[];
extern Gfx d_course_bowsers_castle_dl_38F8[];
extern Gfx d_course_bowsers_castle_dl_39E0[];
extern Gfx d_course_bowsers_castle_dl_3B00[];
extern Gfx d_course_bowsers_castle_dl_3C08[];
extern Gfx d_course_bowsers_castle_dl_3D78[];
extern Gfx d_course_bowsers_castle_dl_3EA8[];
extern Gfx d_course_bowsers_castle_dl_3FF0[];
extern Gfx d_course_bowsers_castle_dl_40F0[];
extern Gfx d_course_bowsers_castle_dl_4278[];
extern Gfx d_course_bowsers_castle_dl_4358[];
extern Gfx d_course_bowsers_castle_dl_4488[];
extern Gfx d_course_bowsers_castle_dl_45D8[];
extern Gfx d_course_bowsers_castle_dl_4748[];
extern Gfx d_course_bowsers_castle_dl_4820[];
extern Gfx d_course_bowsers_castle_dl_4998[];
extern Gfx d_course_bowsers_castle_dl_4A98[];
extern Gfx d_course_bowsers_castle_dl_4C00[];
extern Gfx d_course_bowsers_castle_dl_4CE8[];
extern Gfx d_course_bowsers_castle_dl_4EA8[];
extern struct TrackWayPoint d_course_bowsers_castle_unknown_waypoints[];
extern struct TrackWayPoint d_course_bowsers_castle_track_waypoints[];
extern u8 d_course_bowsers_castle_thwomp_side[];
extern u8 d_course_bowsers_castle_thwomp_tlut[];
extern u8 d_course_bowsers_castle_thwomp_faces[][1024];
extern Vtx d_course_bowsers_castle_thwomp_model1[];
extern Vtx d_course_bowsers_castle_thwomp_model2[];
extern Vtx d_course_bowsers_castle_thwomp_model3[];
extern Vtx d_course_bowsers_castle_thwomp_model4[];
extern Gfx d_course_bowsers_castle_dl_8F38[];
extern Gfx d_course_bowsers_castle_dl_9078[];
extern Gfx d_course_bowsers_castle_dl_thwomp[];
extern Vtx d_course_bowsers_castle_unknown_model[];
extern Gfx d_course_bowsers_castle_dl_bush[];
extern Gfx d_course_bowsers_castle_dl_9148[];
extern Gfx d_course_bowsers_castle_dl_9228[];
extern struct ActorSpawnData d_course_bowsers_castle_tree_spawn[];
extern struct ActorSpawnData d_course_bowsers_castle_item_box_spawns[];
extern TrackSections d_course_bowsers_castle_addr[];

#endif
