#include <ultra64.h>
#include <macros.h>

#include "audio/seqplayer.h"
#include "audio/port_eu.h"
#include "audio/load.h"

OSMesgQueue D_801937C0;
OSMesgQueue D_801937D8;
OSMesgQueue D_801937F0;
OSMesgQueue D_80193808;

struct EuAudioCmd sAudioCmd[0x100];

// Seems oversized by 1
OSMesg D_80194020[2];
OSMesg D_80194028[4];
OSMesg D_80194038[1];
OSMesg D_8019403C[1];

u8 D_800EA3A0[] = { 0, 0, 0, 0 };

u8 D_800EA3A4[] = { 0, 0, 0, 0 };

OSMesgQueue *D_800EA3A8 = &D_801937C0;
OSMesgQueue *D_800EA3AC = &D_801937D8;
OSMesgQueue *D_800EA3B0 = &D_801937F0;
OSMesgQueue *D_800EA3B4 = &D_80193808;

char port_eu_unused_string0[] = "DAC:Lost 1 Frame.\n";
char port_eu_unused_string1[] = "DMA: Request queue over.( %d )\n";
char port_eu_unused_string2[] = "DMA [ %d lines] TIMEOUT\n";
char port_eu_unused_string3[] = "Warning: WaveDmaQ contains %d msgs.\n";
char port_eu_unused_string4[] = "Audio:now-max tasklen is %d / %d\n";
char port_eu_unused_string5[] = "Audio:Warning:ABI Tasklist length over (%d)\n";

s32 D_800EA484 = 128;

char port_eu_unused_string6[] = "AudioSend: %d -> %d (%d)\n";

s32 D_800EA4A4 = 0;

char port_eu_unused_string7[] = "Undefined Port Command %d\n";

#ifdef MIPS_TO_C
//generated by m2c commit eefca95b040d7ee0c617bc58f9ac6cd1cf7bce87 on Aug-14-2023
s32 func_800B70EC(s32, s32 *, s32, s16);            /* extern */
s32 audio_shut_down_and_reset_step();                                /* extern */
? func_800CBCB0(void *);                            /* extern */
extern u8 gAudioResetStatus;
extern u8 gAudioResetPresetIdToLoad;
extern s32 D_803B70B8;
extern s32 D_803B70C0;
extern s32 D_803B70C4;
extern ? gAudioCmdBuffers;
extern s32 gAudioCmd;
extern ? gAudioTasks;
extern ? gAiBuffers;
extern ? D_803B718C;
extern ? aspMainDataEnd;
extern ? aspMainDataStart;
extern ? aspMainTextStart;
extern OSMesgQueue gCurrAudioFrameDmaQueue;

void *create_next_audio_frame_task(void) {
    u32 sp74;
    s32 sp70;
    s32 sp60;
    void *sp58;
    void *sp54;
    s32 *sp40;
    s16 *temp_s1_2;
    s16 temp_v1;
    s32 *temp_a3;
    s32 temp_hi;
    s32 temp_hi_2;
    s32 temp_s1;
    s32 temp_t3;
    s32 var_s0;
    s32 var_s0_2;
    s32 var_s0_3;
    s32 var_s1;

    D_803B70B8 += 1;
    if (((s32) D_803B70B8 % (s16) gAudioBufferParameters.presetUnk4) != 0) {
        return NULL;
    }
    osSendMesg(D_800EA3A8, (void *) D_803B70B8, 0);
    temp_t3 = D_803B70C4 + 1;
    temp_hi = temp_t3 % 3;
    temp_hi_2 = (s32) (temp_hi + 1) % 3;
    D_803B70C4 = temp_t3;
    D_803B70C0 ^= 1;
    D_803B70C4 = temp_hi;
    sp74 = osAiGetLength() >> 2;
    temp_v1 = *(&D_803B718C + (temp_hi_2 * 2));
    if (temp_v1 != 0) {
        osAiSetNextBuffer(*(&gAiBuffers + (temp_hi_2 * 4)), temp_v1 * 4);
    }
    var_s1 = gCurrAudioFrameDmaCount;
    var_s0 = 0;
    if (var_s1 > 0) {
        do {
            if (osRecvMesg(&gCurrAudioFrameDmaQueue, NULL, 0) == 0) {
                var_s1 -= 1;
            }
            var_s0 += 1;
        } while (var_s0 < gCurrAudioFrameDmaCount);
    }
    if (var_s1 != 0) {
        var_s0_2 = 0;
        if (var_s1 > 0) {
            do {
                osRecvMesg(&gCurrAudioFrameDmaQueue, NULL, 1);
                var_s0_2 += 1;
            } while (var_s0_2 != var_s1);
        }
    }
    temp_s1 = gCurrAudioFrameDmaQueue.validCount;
    if (temp_s1 != 0) {
        var_s0_3 = 0;
        if (temp_s1 > 0) {
            do {
                osRecvMesg(&gCurrAudioFrameDmaQueue, NULL, 0);
                var_s0_3 += 1;
            } while (var_s0_3 != temp_s1);
        }
    }
    gCurrAudioFrameDmaCount = 0;
    decrease_sample_dma_ttls();
    if (osRecvMesg(D_800EA3B0, &sp58, 0) != -1) {
        gAudioResetPresetIdToLoad = (u8) sp58;
        gAudioResetStatus = 5;
    }
    if ((gAudioResetStatus != 0) && (audio_shut_down_and_reset_step() == 0)) {
        if (gAudioResetStatus == 0) {
            osSendMesg(D_800EA3B4, (void *) gAudioResetPresetIdToLoad, 0);
        }
        return NULL;
    }
    gAudioTask = (D_803B70C0 * 0x50) + &gAudioTasks;
    temp_a3 = (D_803B70C4 * 4) + &gAiBuffers;
    gAudioCmd = *(&gAudioCmdBuffers + (D_803B70C0 * 4));
    sp60 = *temp_a3;
    temp_s1_2 = (D_803B70C4 * 2) + &D_803B718C;
    *temp_s1_2 = (((gAudioBufferParameters.samplesPerFrameTarget - sp74) + 0x40) & 0xFFF0) + 0x10;
    if (*temp_s1_2 < gAudioBufferParameters.minAiBufferLength) {
        *temp_s1_2 = gAudioBufferParameters.minAiBufferLength;
    }
    if (gAudioBufferParameters.maxAiBufferLength < *temp_s1_2) {
        *temp_s1_2 = gAudioBufferParameters.maxAiBufferLength;
    }
    sp40 = temp_a3;
    if (osRecvMesg(D_800EA3AC, &sp54, 0) != -1) {
        func_800CBCB0(sp54);
    }
    gAudioCmd = func_800B70EC(gAudioCmd, &sp70, sp60, *temp_s1_2);
    gAudioRandom = osGetCount() * (gAudioRandom + D_803B70B8);
    gAudioRandom += *(*sp40 + ((D_803B70B8 & 0xFF) * 2));
    gAudioTask->unk40 = 0;
    gAudioTask->unk44 = 0;
    gAudioTask->unk0 = 2;
    gAudioTask->unk4 = 0;
    gAudioTask->unk8 = rspbootTextStart;
    gAudioTask->unkC = (s32) (rspbootTextEnd - rspbootTextStart);
    gAudioTask->unk10 = &aspMainTextStart;
    gAudioTask->unk18 = &aspMainDataStart;
    gAudioTask->unk14 = 0x00001000;
    gAudioTask->unk1C = (s32) (((s32) (&aspMainDataEnd - &aspMainDataStart) >> 3) * 8);
    gAudioTask->unk20 = 0;
    gAudioTask->unk24 = 0;
    gAudioTask->unk28 = 0;
    gAudioTask->unk2C = 0;
    gAudioTask->unk30 = (s32) *(&gAudioCmdBuffers + (D_803B70C0 * 4));
    gAudioTask->unk38 = 0;
    gAudioTask->unk3C = 0;
    gAudioTask->unk34 = (s32) (sp70 * 8);
    if (D_800EA484 < sp70) {
        D_800EA484 = sp70;
    }
    return gAudioTask;
}
#else
GLOBAL_ASM("asm/non_matchings/audio/port_eu/create_next_audio_frame_task.s")
#endif

void eu_process_audio_cmd(struct EuAudioCmd *cmd) {
    s32 i;

    switch (cmd->u.s.op) {
        case 0x81:
            preload_sequence(cmd->u.s.arg2, 3);
            break;

        case 0x82:
        case 0x88:
            load_sequence(cmd->u.s.arg1, cmd->u.s.arg2, cmd->u.s.arg3);
            func_800CBA64(cmd->u.s.arg1, cmd->u2.as_s32);
            break;

        case 0x83:
            if (gSequencePlayers[cmd->u.s.arg1].enabled != FALSE) {
                if (cmd->u2.as_s32 == 0) {
                    sequence_player_disable(&gSequencePlayers[cmd->u.s.arg1]);
                }
                else {
                    seq_player_fade_to_zero_volume(cmd->u.s.arg1, cmd->u2.as_s32);
                }
            }
            break;

        case 0xf0:
            gAudioLibSoundMode = cmd->u2.as_s32;
            break;

        case 0xf1:
            for (i = 0; i < 4; i++) {
                gSequencePlayers[i].muted = TRUE;
                gSequencePlayers[i].recalculateVolume = TRUE;
            }
            break;

        case 0xf2:
            for (i = 0; i < 4; i++) {
                gSequencePlayers[i].muted = FALSE;
                gSequencePlayers[i].recalculateVolume = TRUE;
            }
            break;
    case 0xF3:
        func_800BB388(cmd->u.s.arg1, cmd->u.s.arg2, cmd->u.s.arg3);
        break;
    }
}

void seq_player_fade_to_zero_volume(s32 arg0, s32 fadeOutTime) {
    struct SequencePlayer *player;

    if (fadeOutTime == 0) {
        fadeOutTime = 1;
    }
    player = &gSequencePlayers[arg0];
    player->state = 2;
    player->fadeRemainingFrames = fadeOutTime;
    player->fadeVelocity = -(player->fadeVolume / fadeOutTime);
}

void func_800CBA64(s32 playerIndex, s32 fadeInTime) {
    struct SequencePlayer *player;

    if (fadeInTime != 0) {
        player = &gSequencePlayers[playerIndex];
        player->state = 1;
        player->fadeTimerUnkEu = fadeInTime;
        player->fadeRemainingFrames = fadeInTime;
        player->fadeVolume = 0.0f;
        player->fadeVelocity = 0.0f;
    }
}

void func_800CBAB4(void) {
    D_800EA3A0[0] = 0;
    D_800EA3A4[0] = 0;
    osCreateMesgQueue(D_800EA3A8, D_80194020, 1);
    osCreateMesgQueue(D_800EA3AC, D_80194028, 4);
    osCreateMesgQueue(D_800EA3B0, D_80194038, 1);
    osCreateMesgQueue(D_800EA3B4, D_8019403C, 1);
}

void func_800CBB48(s32 arg0, s32 *arg1) {
  struct EuAudioCmd *cmd = &sAudioCmd[D_800EA3A0[0] & 0xff];
  cmd->u.first = arg0;
  cmd->u2.as_u32 = *arg1;
  D_800EA3A0[0]++;
}

void func_800CBB88(u32 arg0, f32 arg1) {
    func_800CBB48(arg0, (s32*) &arg1);
}

void func_800CBBB8(u32 arg0, s32 arg1) {
    func_800CBB48(arg0, &arg1);
}

void func_800CBBE8(u32 arg0, s8 arg1) {
    s32 sp34 = arg1 << 24;
    func_800CBB48(arg0, &sp34);
}

// TODO: clenanup, something's weird with the variables. D_800EA4A4 is probably EuAudioCmd bc of the + 0x100
void func_800CBC24(void)
{
  s32 temp_t6;
  s32 test;
  OSMesg thing;
  temp_t6 = D_800EA3A0[0] - D_800EA3A4[0];
  test = (u8) temp_t6;
  test = (test + 0x100) & 0xFF;
  do
  {
  }
  while (0);
  if (D_800EA4A4 < test)
  {
    D_800EA4A4 = test;
  }
  thing = (OSMesg) ((D_800EA3A0[0] & 0xFF) | ((D_800EA3A4[0] & 0xFF) << 8));
  osSendMesg(D_800EA3AC, thing, 0);
  D_800EA3A4[0] = D_800EA3A0[0];
}

#ifdef MIPS_TO_C
//generated by m2c commit 08138748803d75e73e4a94bb0c619a273754ee9c on Sep-13-2023
void func_800CBCB0(u32 arg0) {
    s32 temp_t8;
    s32 var_s1;
    s32 var_v0;
    struct EuAudioCmd *temp_s0;
    struct SequenceChannel *temp_v0_2;
    struct SequencePlayer *temp_v1;
    u8 temp_a0;
    u8 temp_a1;
    u8 temp_v0;
    u8 temp_v1_2;

    temp_t8 = arg0 & 0xFF;
    var_s1 = (arg0 >> 8) & 0xFF;
    var_v0 = var_s1;
    if (temp_t8 != var_s1) {
        do {
            temp_s0 = &D_80193820[var_v0 & 0xFF];
            temp_a0 = temp_s0->u.s.op;
            var_s1 = (var_s1 + 1) & 0xFF;
            if ((temp_a0 & 0xF0) == 0xF0) {
                eu_process_audio_cmd(temp_s0);
            } else {
                temp_v0 = temp_s0->u.s.arg1;
                if ((s32) temp_v0 < 4) {
                    temp_v1 = &gSequencePlayers[temp_v0];
                    if (temp_a0 & 0x80) {
                        eu_process_audio_cmd(temp_s0);
                    } else if (temp_a0 & 0x40) {
                        switch (temp_a0) {          /* switch 1; irregular */
                        case 0x41:                  /* switch 1 */
                            temp_v1->unk0 = (u8) (temp_v1->unk0 | 4);
                            temp_v1->fadeVolumeScale = (bitwise f32) temp_s0->u2.as_s32;
                            break;
                        case 0x47:                  /* switch 1 */
                            temp_v1->tempo = temp_s0->u2.as_s32 * 0x30;
                            break;
                        case 0x48:                  /* switch 1 */
                            temp_v1->transposition = (s16) (s8) temp_s0->u2.as_u8;
                            break;
                        case 0x46:                  /* switch 1 */
                            temp_v1->seqVariationEu[temp_s0->u.s.arg3] = (s8) temp_s0->u2.as_u8;
                            break;
                        }
                    } else if (((u32) temp_v1->unk0 >> 0x1F) != 0) {
                        temp_a1 = temp_s0->u.s.arg2;
                        if ((s32) temp_a1 < 0x10) {
                            temp_v0_2 = temp_v1->channels[temp_a1];
                            if (temp_v0_2 != &gSequenceChannelNone) {
                                switch (temp_a0) {
                                case 1:
                                    temp_v0_2->changes.as_u8 |= 0x40;
                                    temp_v0_2->volumeScale = (bitwise f32) temp_s0->u2.as_s32;
                                    break;
                                case 2:
                                    temp_v0_2->changes.as_u8 |= 0x40;
                                    temp_v0_2->volume = (bitwise f32) temp_s0->u2.as_s32;
                                    break;
                                case 3:
                                    temp_v0_2->changes.as_u8 |= 0x20;
                                    temp_v0_2->newPan = (u8) (s8) temp_s0->u2.as_u8;
                                    break;
                                case 4:
                                    temp_v0_2->changes.as_u8 |= 0x80;
                                    temp_v0_2->freqScale = (bitwise f32) temp_s0->u2.as_s32;
                                    break;
                                case 5:
                                    temp_v0_2->reverbVol = (u8) (s8) temp_s0->u2.as_u8;
                                    break;
                                case 6:
                                    temp_v1_2 = temp_s0->u.s.arg3;
                                    if ((s32) temp_v1_2 < 8) {
                                        temp_v0_2->soundScriptIO[temp_v1_2] = (s8) temp_s0->u2.as_u8;
                                    }
                                    break;
                                case 8:
                                    temp_v0_2->unk0 = (u8) ((((s8) temp_s0->u2.as_u8 * 0x10) & 0x10) | (temp_v0_2->unk0 & 0xFFEF));
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            var_v0 = var_s1;
            temp_s0->u.s.op = 0;
        } while (temp_t8 != var_s1);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/audio/port_eu/func_800CBCB0.s")
#endif

void func_800CBF48() {
    func_800CBAB4();
}
