# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.data

# segment 0x0A000000 (0x729A30 - 0x7E684F)

.align 2, 0x00
glabel gTextureMarioFace00
.incbin "textures/standalone/mario_face_00.rgba16.mio0"
glabel gTextureMarioFace00_end

.align 2, 0x00
glabel gTextureMarioFace01
.incbin "textures/standalone/mario_face_01.rgba16.mio0"
glabel gTextureMarioFace01_end

.align 2, 0x00
glabel gTextureMarioFace02
.incbin "textures/standalone/mario_face_02.rgba16.mio0"
glabel gTextureMarioFace02_end

.align 2, 0x00
glabel gTextureMarioFace03
.incbin "textures/standalone/mario_face_03.rgba16.mio0"
glabel gTextureMarioFace03_end

.align 2, 0x00
glabel gTextureMarioFace04
.incbin "textures/standalone/mario_face_04.rgba16.mio0"
glabel gTextureMarioFace04_end

.align 2, 0x00
glabel gTextureMarioFace05
.incbin "textures/standalone/mario_face_05.rgba16.mio0"
glabel gTextureMarioFace05_end

.align 2, 0x00
glabel gTextureMarioFace06
.incbin "textures/standalone/mario_face_06.rgba16.mio0"
glabel gTextureMarioFace06_end

.align 2, 0x00
glabel gTextureMarioFace07
.incbin "textures/standalone/mario_face_07.rgba16.mio0"
glabel gTextureMarioFace07_end

.align 2, 0x00
glabel gTextureMarioFace08
.incbin "textures/standalone/mario_face_08.rgba16.mio0"
glabel gTextureMarioFace08_end

.align 2, 0x00
glabel gTextureMarioFace09
.incbin "textures/standalone/mario_face_09.rgba16.mio0"
glabel gTextureMarioFace09_end

.align 2, 0x00
glabel gTextureMarioFace10
.incbin "textures/standalone/mario_face_10.rgba16.mio0"
glabel gTextureMarioFace10_end

.align 2, 0x00
glabel gTextureMarioFace11
.incbin "textures/standalone/mario_face_11.rgba16.mio0"
glabel gTextureMarioFace11_end

.align 2, 0x00
glabel gTextureMarioFace12
.incbin "textures/standalone/mario_face_12.rgba16.mio0"
glabel gTextureMarioFace12_end

.align 2, 0x00
glabel gTextureMarioFace13
.incbin "textures/standalone/mario_face_13.rgba16.mio0"
glabel gTextureMarioFace13_end

.align 2, 0x00
glabel gTextureMarioFace14
.incbin "textures/standalone/mario_face_14.rgba16.mio0"
glabel gTextureMarioFace14_end

.align 2, 0x00
glabel gTextureMarioFace15
.incbin "textures/standalone/mario_face_15.rgba16.mio0"
glabel gTextureMarioFace15_end

.align 2, 0x00
glabel gTextureMarioFace16
.incbin "textures/standalone/mario_face_16.rgba16.mio0"
glabel gTextureMarioFace16_end

.align 2, 0x00
glabel gTextureLuigiFace00
.incbin "textures/standalone/luigi_face_00.rgba16.mio0"
glabel gTextureLuigiFace00_end

.align 2, 0x00
glabel gTextureLuigiFace01
.incbin "textures/standalone/luigi_face_01.rgba16.mio0"
glabel gTextureLuigiFace01_end

.align 2, 0x00
glabel gTextureLuigiFace02
.incbin "textures/standalone/luigi_face_02.rgba16.mio0"
glabel gTextureLuigiFace02_end

.align 2, 0x00
glabel gTextureLuigiFace03
.incbin "textures/standalone/luigi_face_03.rgba16.mio0"
glabel gTextureLuigiFace03_end

.align 2, 0x00
glabel gTextureLuigiFace04
.incbin "textures/standalone/luigi_face_04.rgba16.mio0"
glabel gTextureLuigiFace04_end

.align 2, 0x00
glabel gTextureLuigiFace05
.incbin "textures/standalone/luigi_face_05.rgba16.mio0"
glabel gTextureLuigiFace05_end

.align 2, 0x00
glabel gTextureLuigiFace06
.incbin "textures/standalone/luigi_face_06.rgba16.mio0"
glabel gTextureLuigiFace06_end

.align 2, 0x00
glabel gTextureLuigiFace07
.incbin "textures/standalone/luigi_face_07.rgba16.mio0"
glabel gTextureLuigiFace07_end

.align 2, 0x00
glabel gTextureLuigiFace08
.incbin "textures/standalone/luigi_face_08.rgba16.mio0"
glabel gTextureLuigiFace08_end

.align 2, 0x00
glabel gTextureLuigiFace09
.incbin "textures/standalone/luigi_face_09.rgba16.mio0"
glabel gTextureLuigiFace09_end

.align 2, 0x00
glabel gTextureLuigiFace10
.incbin "textures/standalone/luigi_face_10.rgba16.mio0"
glabel gTextureLuigiFace10_end

.align 2, 0x00
glabel gTextureLuigiFace11
.incbin "textures/standalone/luigi_face_11.rgba16.mio0"
glabel gTextureLuigiFace11_end

.align 2, 0x00
glabel gTextureLuigiFace12
.incbin "textures/standalone/luigi_face_12.rgba16.mio0"
glabel gTextureLuigiFace12_end

.align 2, 0x00
glabel gTextureLuigiFace13
.incbin "textures/standalone/luigi_face_13.rgba16.mio0"
glabel gTextureLuigiFace13_end

.align 2, 0x00
glabel gTextureLuigiFace14
.incbin "textures/standalone/luigi_face_14.rgba16.mio0"
glabel gTextureLuigiFace14_end

.align 2, 0x00
glabel gTextureLuigiFace15
.incbin "textures/standalone/luigi_face_15.rgba16.mio0"
glabel gTextureLuigiFace15_end

.align 2, 0x00
glabel gTextureLuigiFace16
.incbin "textures/standalone/luigi_face_16.rgba16.mio0"
glabel gTextureLuigiFace16_end

.align 2, 0x00
glabel gTexturePeachFace00
.incbin "textures/standalone/peach_face_00.rgba16.mio0"
glabel gTexturePeachFace00_end

.align 2, 0x00
glabel gTexturePeachFace01
.incbin "textures/standalone/peach_face_01.rgba16.mio0"
glabel gTexturePeachFace01_end

.align 2, 0x00
glabel gTexturePeachFace02
.incbin "textures/standalone/peach_face_02.rgba16.mio0"
glabel gTexturePeachFace02_end

.align 2, 0x00
glabel gTexturePeachFace03
.incbin "textures/standalone/peach_face_03.rgba16.mio0"
glabel gTexturePeachFace03_end

.align 2, 0x00
glabel gTexturePeachFace04
.incbin "textures/standalone/peach_face_04.rgba16.mio0"
glabel gTexturePeachFace04_end

.align 2, 0x00
glabel gTexturePeachFace05
.incbin "textures/standalone/peach_face_05.rgba16.mio0"
glabel gTexturePeachFace05_end

.align 2, 0x00
glabel gTexturePeachFace06
.incbin "textures/standalone/peach_face_06.rgba16.mio0"
glabel gTexturePeachFace06_end

.align 2, 0x00
glabel gTexturePeachFace07
.incbin "textures/standalone/peach_face_07.rgba16.mio0"
glabel gTexturePeachFace07_end

.align 2, 0x00
glabel gTexturePeachFace08
.incbin "textures/standalone/peach_face_08.rgba16.mio0"
glabel gTexturePeachFace08_end

.align 2, 0x00
glabel gTexturePeachFace09
.incbin "textures/standalone/peach_face_09.rgba16.mio0"
glabel gTexturePeachFace09_end

.align 2, 0x00
glabel gTexturePeachFace10
.incbin "textures/standalone/peach_face_10.rgba16.mio0"
glabel gTexturePeachFace10_end

.align 2, 0x00
glabel gTexturePeachFace11
.incbin "textures/standalone/peach_face_11.rgba16.mio0"
glabel gTexturePeachFace11_end

.align 2, 0x00
glabel gTexturePeachFace12
.incbin "textures/standalone/peach_face_12.rgba16.mio0"
glabel gTexturePeachFace12_end

.align 2, 0x00
glabel gTexturePeachFace13
.incbin "textures/standalone/peach_face_13.rgba16.mio0"
glabel gTexturePeachFace13_end

.align 2, 0x00
glabel gTexturePeachFace14
.incbin "textures/standalone/peach_face_14.rgba16.mio0"
glabel gTexturePeachFace14_end

.align 2, 0x00
glabel gTexturePeachFace15
.incbin "textures/standalone/peach_face_15.rgba16.mio0"
glabel gTexturePeachFace15_end

.align 2, 0x00
glabel gTexturePeachFace16
.incbin "textures/standalone/peach_face_16.rgba16.mio0"
glabel gTexturePeachFace16_end

.align 2, 0x00
glabel gTextureToadFace00
.incbin "textures/standalone/toad_face_00.rgba16.mio0"
glabel gTextureToadFace00_end

.align 2, 0x00
glabel gTextureToadFace01
.incbin "textures/standalone/toad_face_01.rgba16.mio0"
glabel gTextureToadFace01_end

.align 2, 0x00
glabel gTextureToadFace02
.incbin "textures/standalone/toad_face_02.rgba16.mio0"
glabel gTextureToadFace02_end

.align 2, 0x00
glabel gTextureToadFace03
.incbin "textures/standalone/toad_face_03.rgba16.mio0"
glabel gTextureToadFace03_end

.align 2, 0x00
glabel gTextureToadFace04
.incbin "textures/standalone/toad_face_04.rgba16.mio0"
glabel gTextureToadFace04_end

.align 2, 0x00
glabel gTextureToadFace05
.incbin "textures/standalone/toad_face_05.rgba16.mio0"
glabel gTextureToadFace05_end

.align 2, 0x00
glabel gTextureToadFace06
.incbin "textures/standalone/toad_face_06.rgba16.mio0"
glabel gTextureToadFace06_end

.align 2, 0x00
glabel gTextureToadFace07
.incbin "textures/standalone/toad_face_07.rgba16.mio0"
glabel gTextureToadFace07_end

.align 2, 0x00
glabel gTextureToadFace08
.incbin "textures/standalone/toad_face_08.rgba16.mio0"
glabel gTextureToadFace08_end

.align 2, 0x00
glabel gTextureToadFace09
.incbin "textures/standalone/toad_face_09.rgba16.mio0"
glabel gTextureToadFace09_end

.align 2, 0x00
glabel gTextureToadFace10
.incbin "textures/standalone/toad_face_10.rgba16.mio0"
glabel gTextureToadFace10_end

.align 2, 0x00
glabel gTextureToadFace11
.incbin "textures/standalone/toad_face_11.rgba16.mio0"
glabel gTextureToadFace11_end

.align 2, 0x00
glabel gTextureToadFace12
.incbin "textures/standalone/toad_face_12.rgba16.mio0"
glabel gTextureToadFace12_end

.align 2, 0x00
glabel gTextureToadFace13
.incbin "textures/standalone/toad_face_13.rgba16.mio0"
glabel gTextureToadFace13_end

.align 2, 0x00
glabel gTextureToadFace14
.incbin "textures/standalone/toad_face_14.rgba16.mio0"
glabel gTextureToadFace14_end

.align 2, 0x00
glabel gTextureToadFace15
.incbin "textures/standalone/toad_face_15.rgba16.mio0"
glabel gTextureToadFace15_end

.align 2, 0x00
glabel gTextureToadFace16
.incbin "textures/standalone/toad_face_16.rgba16.mio0"
glabel gTextureToadFace16_end

.align 2, 0x00
glabel gTextureYoshiFace00
.incbin "textures/standalone/yoshi_face_00.rgba16.mio0"
glabel gTextureYoshiFace00_end

.align 2, 0x00
glabel gTextureYoshiFace01
.incbin "textures/standalone/yoshi_face_01.rgba16.mio0"
glabel gTextureYoshiFace01_end

.align 2, 0x00
glabel gTextureYoshiFace02
.incbin "textures/standalone/yoshi_face_02.rgba16.mio0"
glabel gTextureYoshiFace02_end

.align 2, 0x00
glabel gTextureYoshiFace03
.incbin "textures/standalone/yoshi_face_03.rgba16.mio0"
glabel gTextureYoshiFace03_end

.align 2, 0x00
glabel gTextureYoshiFace04
.incbin "textures/standalone/yoshi_face_04.rgba16.mio0"
glabel gTextureYoshiFace04_end

.align 2, 0x00
glabel gTextureYoshiFace05
.incbin "textures/standalone/yoshi_face_05.rgba16.mio0"
glabel gTextureYoshiFace05_end

.align 2, 0x00
glabel gTextureYoshiFace06
.incbin "textures/standalone/yoshi_face_06.rgba16.mio0"
glabel gTextureYoshiFace06_end

.align 2, 0x00
glabel gTextureYoshiFace07
.incbin "textures/standalone/yoshi_face_07.rgba16.mio0"
glabel gTextureYoshiFace07_end

.align 2, 0x00
glabel gTextureYoshiFace08
.incbin "textures/standalone/yoshi_face_08.rgba16.mio0"
glabel gTextureYoshiFace08_end

.align 2, 0x00
glabel gTextureYoshiFace09
.incbin "textures/standalone/yoshi_face_09.rgba16.mio0"
glabel gTextureYoshiFace09_end

.align 2, 0x00
glabel gTextureYoshiFace10
.incbin "textures/standalone/yoshi_face_10.rgba16.mio0"
glabel gTextureYoshiFace10_end

.align 2, 0x00
glabel gTextureYoshiFace11
.incbin "textures/standalone/yoshi_face_11.rgba16.mio0"
glabel gTextureYoshiFace11_end

.align 2, 0x00
glabel gTextureYoshiFace12
.incbin "textures/standalone/yoshi_face_12.rgba16.mio0"
glabel gTextureYoshiFace12_end

.align 2, 0x00
glabel gTextureYoshiFace13
.incbin "textures/standalone/yoshi_face_13.rgba16.mio0"
glabel gTextureYoshiFace13_end

.align 2, 0x00
glabel gTextureYoshiFace14
.incbin "textures/standalone/yoshi_face_14.rgba16.mio0"
glabel gTextureYoshiFace14_end

.align 2, 0x00
glabel gTextureYoshiFace15
.incbin "textures/standalone/yoshi_face_15.rgba16.mio0"
glabel gTextureYoshiFace15_end

.align 2, 0x00
glabel gTextureYoshiFace16
.incbin "textures/standalone/yoshi_face_16.rgba16.mio0"
glabel gTextureYoshiFace16_end

.align 2, 0x00
glabel gTextureDkFace00
.incbin "textures/standalone/dk_face_00.rgba16.mio0"
glabel gTextureDkFace00_end

.align 2, 0x00
glabel gTextureDkFace01
.incbin "textures/standalone/dk_face_01.rgba16.mio0"
glabel gTextureDkFace01_end

.align 2, 0x00
glabel gTextureDkFace02
.incbin "textures/standalone/dk_face_02.rgba16.mio0"
glabel gTextureDkFace02_end

.align 2, 0x00
glabel gTextureDkFace03
.incbin "textures/standalone/dk_face_03.rgba16.mio0"
glabel gTextureDkFace03_end

.align 2, 0x00
glabel gTextureDkFace04
.incbin "textures/standalone/dk_face_04.rgba16.mio0"
glabel gTextureDkFace04_end

.align 2, 0x00
glabel gTextureDkFace05
.incbin "textures/standalone/dk_face_05.rgba16.mio0"
glabel gTextureDkFace05_end

.align 2, 0x00
glabel gTextureDkFace06
.incbin "textures/standalone/dk_face_06.rgba16.mio0"
glabel gTextureDkFace06_end

.align 2, 0x00
glabel gTextureDkFace07
.incbin "textures/standalone/dk_face_07.rgba16.mio0"
glabel gTextureDkFace07_end

.align 2, 0x00
glabel gTextureDkFace08
.incbin "textures/standalone/dk_face_08.rgba16.mio0"
glabel gTextureDkFace08_end

.align 2, 0x00
glabel gTextureDkFace09
.incbin "textures/standalone/dk_face_09.rgba16.mio0"
glabel gTextureDkFace09_end

.align 2, 0x00
glabel gTextureDkFace10
.incbin "textures/standalone/dk_face_10.rgba16.mio0"
glabel gTextureDkFace10_end

.align 2, 0x00
glabel gTextureDkFace11
.incbin "textures/standalone/dk_face_11.rgba16.mio0"
glabel gTextureDkFace11_end

.align 2, 0x00
glabel gTextureDkFace12
.incbin "textures/standalone/dk_face_12.rgba16.mio0"
glabel gTextureDkFace12_end

.align 2, 0x00
glabel gTextureDkFace13
.incbin "textures/standalone/dk_face_13.rgba16.mio0"
glabel gTextureDkFace13_end

.align 2, 0x00
glabel gTextureDkFace14
.incbin "textures/standalone/dk_face_14.rgba16.mio0"
glabel gTextureDkFace14_end

.align 2, 0x00
glabel gTextureDkFace15
.incbin "textures/standalone/dk_face_15.rgba16.mio0"
glabel gTextureDkFace15_end

.align 2, 0x00
glabel gTextureDkFace16
.incbin "textures/standalone/dk_face_16.rgba16.mio0"
glabel gTextureDkFace16_end

.align 2, 0x00
glabel gTextureWarioFace00
.incbin "textures/standalone/wario_face_00.rgba16.mio0"
glabel gTextureWarioFace00_end

.align 2, 0x00
glabel gTextureWarioFace01
.incbin "textures/standalone/wario_face_01.rgba16.mio0"
glabel gTextureWarioFace01_end

.align 2, 0x00
glabel gTextureWarioFace02
.incbin "textures/standalone/wario_face_02.rgba16.mio0"
glabel gTextureWarioFace02_end

.align 2, 0x00
glabel gTextureWarioFace03
.incbin "textures/standalone/wario_face_03.rgba16.mio0"
glabel gTextureWarioFace03_end

.align 2, 0x00
glabel gTextureWarioFace04
.incbin "textures/standalone/wario_face_04.rgba16.mio0"
glabel gTextureWarioFace04_end

.align 2, 0x00
glabel gTextureWarioFace05
.incbin "textures/standalone/wario_face_05.rgba16.mio0"
glabel gTextureWarioFace05_end

.align 2, 0x00
glabel gTextureWarioFace06
.incbin "textures/standalone/wario_face_06.rgba16.mio0"
glabel gTextureWarioFace06_end

.align 2, 0x00
glabel gTextureWarioFace07
.incbin "textures/standalone/wario_face_07.rgba16.mio0"
glabel gTextureWarioFace07_end

.align 2, 0x00
glabel gTextureWarioFace08
.incbin "textures/standalone/wario_face_08.rgba16.mio0"
glabel gTextureWarioFace08_end

.align 2, 0x00
glabel gTextureWarioFace09
.incbin "textures/standalone/wario_face_09.rgba16.mio0"
glabel gTextureWarioFace09_end

.align 2, 0x00
glabel gTextureWarioFace10
.incbin "textures/standalone/wario_face_10.rgba16.mio0"
glabel gTextureWarioFace10_end

.align 2, 0x00
glabel gTextureWarioFace11
.incbin "textures/standalone/wario_face_11.rgba16.mio0"
glabel gTextureWarioFace11_end

.align 2, 0x00
glabel gTextureWarioFace12
.incbin "textures/standalone/wario_face_12.rgba16.mio0"
glabel gTextureWarioFace12_end

.align 2, 0x00
glabel gTextureWarioFace13
.incbin "textures/standalone/wario_face_13.rgba16.mio0"
glabel gTextureWarioFace13_end

.align 2, 0x00
glabel gTextureWarioFace14
.incbin "textures/standalone/wario_face_14.rgba16.mio0"
glabel gTextureWarioFace14_end

.align 2, 0x00
glabel gTextureWarioFace15
.incbin "textures/standalone/wario_face_15.rgba16.mio0"
glabel gTextureWarioFace15_end

.align 2, 0x00
glabel gTextureWarioFace16
.incbin "textures/standalone/wario_face_16.rgba16.mio0"
glabel gTextureWarioFace16_end

.align 2, 0x00
glabel gTextureBowserFace00
.incbin "textures/standalone/bowser_face_00.rgba16.mio0"
glabel gTextureBowserFace00_end

.align 2, 0x00
glabel gTextureBowserFace01
.incbin "textures/standalone/bowser_face_01.rgba16.mio0"
glabel gTextureBowserFace01_end

.align 2, 0x00
glabel gTextureBowserFace02
.incbin "textures/standalone/bowser_face_02.rgba16.mio0"
glabel gTextureBowserFace02_end

.align 2, 0x00
glabel gTextureBowserFace03
.incbin "textures/standalone/bowser_face_03.rgba16.mio0"
glabel gTextureBowserFace03_end

.align 2, 0x00
glabel gTextureBowserFace04
.incbin "textures/standalone/bowser_face_04.rgba16.mio0"
glabel gTextureBowserFace04_end

.align 2, 0x00
glabel gTextureBowserFace05
.incbin "textures/standalone/bowser_face_05.rgba16.mio0"
glabel gTextureBowserFace05_end

.align 2, 0x00
glabel gTextureBowserFace06
.incbin "textures/standalone/bowser_face_06.rgba16.mio0"
glabel gTextureBowserFace06_end

.align 2, 0x00
glabel gTextureBowserFace07
.incbin "textures/standalone/bowser_face_07.rgba16.mio0"
glabel gTextureBowserFace07_end

.align 2, 0x00
glabel gTextureBowserFace08
.incbin "textures/standalone/bowser_face_08.rgba16.mio0"
glabel gTextureBowserFace08_end

.align 2, 0x00
glabel gTextureBowserFace09
.incbin "textures/standalone/bowser_face_09.rgba16.mio0"
glabel gTextureBowserFace09_end

.align 2, 0x00
glabel gTextureBowserFace10
.incbin "textures/standalone/bowser_face_10.rgba16.mio0"
glabel gTextureBowserFace10_end

.align 2, 0x00
glabel gTextureBowserFace11
.incbin "textures/standalone/bowser_face_11.rgba16.mio0"
glabel gTextureBowserFace11_end

.align 2, 0x00
glabel gTextureBowserFace12
.incbin "textures/standalone/bowser_face_12.rgba16.mio0"
glabel gTextureBowserFace12_end

.align 2, 0x00
glabel gTextureBowserFace13
.incbin "textures/standalone/bowser_face_13.rgba16.mio0"
glabel gTextureBowserFace13_end

.align 2, 0x00
glabel gTextureBowserFace14
.incbin "textures/standalone/bowser_face_14.rgba16.mio0"
glabel gTextureBowserFace14_end

.align 2, 0x00
glabel gTextureBowserFace15
.incbin "textures/standalone/bowser_face_15.rgba16.mio0"
glabel gTextureBowserFace15_end

.align 2, 0x00
glabel gTextureBowserFace16
.incbin "textures/standalone/bowser_face_16.rgba16.mio0"
glabel gTextureBowserFace16_end

.align 2, 0x00
glabel gCoursePreviewMarioRaceway
.incbin "textures/standalone/course_preview_mario_raceway.rgba16.mio0"
glabel gCoursePreviewMarioRaceway_end

.align 2, 0x00
glabel gCoursePreviewChocoMountain
.incbin "textures/standalone/course_preview_choco_mountain.rgba16.mio0"
glabel gCoursePreviewChocoMountain_end

.align 2, 0x00
glabel gCoursePreviewBowsersCastle
.incbin "textures/standalone/course_preview_bowsers_castle.rgba16.mio0"
glabel gCoursePreviewBowsersCastle_end

.align 2, 0x00
glabel gCoursePreviewBansheeBoardwalk
.incbin "textures/standalone/course_preview_banshee_boardwalk.rgba16.mio0"
glabel gCoursePreviewBansheeBoardwalk_end

.align 2, 0x00
glabel gCoursePreviewYoshiValley
.incbin "textures/standalone/course_preview_yoshi_valley.rgba16.mio0"
glabel gCoursePreviewYoshiValley_end

.align 2, 0x00
glabel gCoursePreviewFrappeSnowland
.incbin "textures/standalone/course_preview_frappe_snowland.rgba16.mio0"
glabel gCoursePreviewFrappeSnowland_end

.align 2, 0x00
glabel gCoursePreviewKoopaTroopaBeach
.incbin "textures/standalone/course_preview_koopa_troopa_beach.rgba16.mio0"
glabel gCoursePreviewKoopaTroopaBeach_end

.align 2, 0x00
glabel gCoursePreviewRoyalRaceway
.incbin "textures/standalone/course_preview_royal_raceway.rgba16.mio0"
glabel gCoursePreviewRoyalRaceway_end

.align 2, 0x00
glabel gCoursePreviewLuigiRaceway
.incbin "textures/standalone/course_preview_luigi_raceway.rgba16.mio0"
glabel gCoursePreviewLuigiRaceway_end

.align 2, 0x00
glabel gCoursePreviewMooMooFarm
.incbin "textures/standalone/course_preview_moo_moo_farm.rgba16.mio0"
glabel gCoursePreviewMooMooFarm_end

.align 2, 0x00
glabel gCoursePreviewToadsTurnpike
.incbin "textures/standalone/course_preview_toads_turnpike.rgba16.mio0"
glabel gCoursePreviewToadsTurnpike_end

.align 2, 0x00
glabel gCoursePreviewKalimariDesert
.incbin "textures/standalone/course_preview_kalimari_desert.rgba16.mio0"
glabel gCoursePreviewKalimariDesert_end

.align 2, 0x00
glabel gCoursePreviewSherbetLand
.incbin "textures/standalone/course_preview_sherbet_land.rgba16.mio0"
glabel gCoursePreviewSherbetLand_end

.align 2, 0x00
glabel gCoursePreviewRainbowRoad
.incbin "textures/standalone/course_preview_rainbow_road.rgba16.mio0"
glabel gCoursePreviewRainbowRoad_end

.align 2, 0x00
glabel gCoursePreviewWarioStadium
.incbin "textures/standalone/course_preview_wario_stadium.rgba16.mio0"
glabel gCoursePreviewWarioStadium_end

.align 2, 0x00
glabel gCoursePreviewBlockFort
.incbin "textures/standalone/course_preview_block_fort.rgba16.mio0"
glabel gCoursePreviewBlockFort_end

.align 2, 0x00
glabel gCoursePreviewSkyscraper
.incbin "textures/standalone/course_preview_skyscraper.rgba16.mio0"
glabel gCoursePreviewSkyscraper_end

.align 2, 0x00
glabel gCoursePreviewDoubleDeck
.incbin "textures/standalone/course_preview_double_deck.rgba16.mio0"
glabel gCoursePreviewDoubleDeck_end

.align 2, 0x00
glabel gCoursePreviewDksJungleParkway
.incbin "textures/standalone/course_preview_dks_jungle_parkway.rgba16.mio0"
glabel gCoursePreviewDksJungleParkway_end

.align 2, 0x00
glabel gCoursePreviewBigDonut
.incbin "textures/standalone/course_preview_big_donut.rgba16.mio0"
glabel gCoursePreviewBigDonut_end

.align 2, 0x00
glabel gTextureTrophyGold
.incbin "textures/standalone/trophy_gold.rgba16.mio0"
glabel gTextureTrophyGold_end

.align 2, 0x00
glabel gTextureTrophySilver
.incbin "textures/standalone/trophy_silver.rgba16.mio0"
glabel gTextureTrophySilver_end

.align 2, 0x00
glabel gTextureTrophyBronze
.incbin "textures/standalone/trophy_bronze.rgba16.mio0"
glabel gTextureTrophyBronze_end

.align 2, 0x00
glabel gTextureCupGold
.incbin "textures/standalone/cup_gold.rgba16.mio0"
glabel gTextureCupGold_end

.align 2, 0x00
glabel gTextureCupSilver
.incbin "textures/standalone/cup_silver.rgba16.mio0"
glabel gTextureCupSilver_end

.align 2, 0x00
glabel gTextureCupBronze
.incbin "textures/standalone/cup_bronze.rgba16.mio0"
glabel gTextureCupBronze_end

.align 2, 0x00
glabel gTexturePushStartButton
.incbin "textures/raw/push_start_button.rgba16"

.align 2, 0x00
glabel gTextureCopyright1996
.incbin "textures/raw/copyright_1996.rgba16"

.align 2, 0x00
glabel gTextureP1BorderBlue
.incbin "textures/raw/p1_border_blue.rgba16"

.align 2, 0x00
glabel gTextureP2BorderRed
.incbin "textures/raw/p2_border_red.rgba16"

.align 2, 0x00
glabel gTextureP3BorderOrange
.incbin "textures/raw/p3_border_orange.rgba16"

.align 2, 0x00
glabel gTextureP4BorderGreen
.incbin "textures/raw/p4_border_green.rgba16"

.align 2, 0x00
glabel gTextureSmallGreenTriangle
.incbin "textures/raw/small_green_triangle.rgba16"

.align 2, 0x00
glabel gTexture7E56E4
.incbin "textures/standalone/texture_7E56E4.ia16.mio0"
glabel gTexture7E56E4_end

