# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.section .data

glabel D_800DDB50
.byte 0x00, 0x02, 0x00, 0x01, 0x00, 0x01, 0x00, 0x02

glabel D_800DDB58
.word 0x00000000, gFramebuffer0, gFramebuffer1, gFramebuffer2

glabel D_800DDB68
.word D_800ED600, D_800ED608, D_800ED610, D_800ED618
.word D_800ED620, D_800ED628, D_800ED630, D_800ED638

glabel D_800DDB88
.word D_800ED640, D_800ED648, D_800ED650, D_800ED658
.word D_800ED660, D_800ED668, D_800ED670, D_800ED678
.word 0x00000000, 0x00000000, 0x00000000

glabel D_800DDBB4
.word D_800E49C0, D_800E4AC0, D_800E4BC0, D_800E4CC0
.word D_800E4DC0, D_800E4EC0, D_800E4FD0, D_800E50D0

glabel D_800DDBD4
.float 0.75, 0.75, 0.75, 0.75
.float 0.75, 0.75, 0.75, 0.75

glabel gKartMarioWheels0
.word gKartMario168Wheel0, gKartMario147Wheel0, gKartMario126Wheel0, gKartMario105Wheel0
.word gKartMario084Wheel0, gKartMario063Wheel0, gKartMario042Wheel0, gKartMario021Wheel0
.word gKartMario000Wheel0

glabel gKartMarioWheels1
.word gKartMario269Wheel0, gKartMario269Wheel0, gKartMario249Wheel0, gKartMario229Wheel0
.word gKartMario229Wheel0, gKartMario229Wheel0, gKartMario209Wheel0, gKartMario189Wheel0
.word gKartMario189Wheel0

glabel gKartLuigiWheels0
.word gKartLuigi168Wheel0, gKartLuigi147Wheel0, gKartLuigi126Wheel0, gKartLuigi105Wheel0
.word gKartLuigi084Wheel0, gKartLuigi063Wheel0, gKartLuigi042Wheel0, gKartLuigi021Wheel0
.word gKartLuigi000Wheel0

glabel gKartLuigiWheels1
.word gKartLuigi269Wheel0, gKartLuigi269Wheel0, gKartLuigi249Wheel0, gKartLuigi229Wheel0
.word gKartLuigi229Wheel0, gKartLuigi229Wheel0, gKartLuigi209Wheel0, gKartLuigi189Wheel0
.word gKartLuigi189Wheel0

glabel gKartBowserWheels0
.word gKartBowser168Wheel0, gKartBowser147Wheel0, gKartBowser126Wheel0, gKartBowser105Wheel0
.word gKartBowser084Wheel0, gKartBowser063Wheel0, gKartBowser042Wheel0, gKartBowser021Wheel0
.word gKartBowser000Wheel0

glabel gKartBowserWheels1
.word gKartBowser269Wheel0, gKartBowser269Wheel0, gKartBowser249Wheel0, gKartBowser229Wheel0
.word gKartBowser229Wheel0, gKartBowser229Wheel0, gKartBowser209Wheel0, gKartBowser189Wheel0
.word gKartBowser189Wheel0

glabel gKartToadWheels0
.word gKartToad168Wheel0, gKartToad147Wheel0, gKartToad126Wheel0, gKartToad105Wheel0
.word gKartToad084Wheel0, gKartToad063Wheel0, gKartToad042Wheel0, gKartToad021Wheel0
.word gKartToad000Wheel0

glabel gKartToadWheels1
.word gKartToad269Wheel0, gKartToad269Wheel0, gKartToad249Wheel0, gKartToad229Wheel0
.word gKartToad229Wheel0, gKartToad229Wheel0, gKartToad209Wheel0, gKartToad189Wheel0
.word gKartToad189Wheel0

glabel gKartYoshiWheels0
.word gKartYoshi168Wheel0, gKartYoshi147Wheel0, gKartYoshi126Wheel0, gKartYoshi105Wheel0
.word gKartYoshi084Wheel0, gKartYoshi063Wheel0, gKartYoshi042Wheel0, gKartYoshi021Wheel0
.word gKartYoshi000Wheel0

glabel gKartYoshiWheels1
.word gKartYoshi269Wheel0, gKartYoshi269Wheel0, gKartYoshi249Wheel0, gKartYoshi229Wheel0
.word gKartYoshi229Wheel0, gKartYoshi229Wheel0, gKartYoshi209Wheel0, gKartYoshi189Wheel0
.word gKartYoshi189Wheel0

glabel gKartDKWheels0
.word gKartDK168Wheel0, gKartDK147Wheel0, gKartDK126Wheel0, gKartDK105Wheel0
.word gKartDK084Wheel0, gKartDK063Wheel0, gKartDK042Wheel0, gKartDK021Wheel0
.word gKartDK000Wheel0

glabel gKartDKWheels1
.word gKartDK269Wheel0, gKartDK269Wheel0, gKartDK249Wheel0, gKartDK229Wheel0
.word gKartDK229Wheel0, gKartDK229Wheel0, gKartDK209Wheel0, gKartDK189Wheel0
.word gKartDK189Wheel0

glabel gKartPeachWheels0
.word gKartPeach168Wheel0, gKartPeach147Wheel0, gKartPeach126Wheel0, gKartPeach105Wheel0
.word gKartPeach084Wheel0, gKartPeach063Wheel0, gKartPeach042Wheel0, gKartPeach021Wheel0
.word gKartPeach000Wheel0

glabel gKartPeachWheels1
.word gKartPeach269Wheel0, gKartPeach269Wheel0, gKartPeach249Wheel0, gKartPeach229Wheel0
.word gKartPeach229Wheel0, gKartPeach229Wheel0, gKartPeach209Wheel0, gKartPeach189Wheel0
.word gKartPeach189Wheel0

glabel gKartWarioWheels0
.word gKartWario168Wheel0, gKartWario147Wheel0, gKartWario126Wheel0, gKartWario105Wheel0
.word gKartWario084Wheel0, gKartWario063Wheel0, gKartWario042Wheel0, gKartWario021Wheel0
.word gKartWario000Wheel0

glabel gKartWarioWheels1
.word gKartWario269Wheel0, gKartWario269Wheel0, gKartWario249Wheel0, gKartWario229Wheel0
.word gKartWario229Wheel0, gKartWario229Wheel0, gKartWario209Wheel0, gKartWario189Wheel0
.word gKartWario189Wheel0

glabel D_800DDE34
.word gKartMarioWheels0, gKartLuigiWheels0, gKartYoshiWheels0, gKartToadWheels0
.word gKartDKWheels0,    gKartWarioWheels0, gKartPeachWheels0, gKartBowserWheels0

glabel D_800DDE54
.word gKartMarioWheels1, gKartLuigiWheels1, gKartYoshiWheels1, gKartToadWheels1
.word gKartDKWheels1,    gKartWarioWheels1, gKartPeachWheels1, gKartBowserWheels1

# array size of 9?
glabel D_800DDE74
.word 0x00000060, 0x00000080, 0x000000c0, 0x00000100
.word 0x00000120, 0x00000180, 0x00000200, 0x00000220
.word 0x00000240

# padding?
.word 0x00000000

glabel D_800DDE9C
.word 0x41100000, 0x40e00000, 0x40a00000

.word 0x00000000, 0x00000000

glabel D_800DDEB0
.hword 0x06c0, 0x06e0, 0x06e0, 0x0680, 0x07c0, 0x0700, 0x0680, 0x0910

glabel gKartMarioGroup0
.word gKartMario000, gKartMario001, gKartMario002, gKartMario003
.word gKartMario004, gKartMario005, gKartMario006, gKartMario007
.word gKartMario008, gKartMario009, gKartMario010, gKartMario011
.word gKartMario012, gKartMario013, gKartMario014, gKartMario015
.word gKartMario016, gKartMario017, gKartMario018, gKartMario019
.word gKartMario020, gKartMario195, gKartMario196, gKartMario197
.word gKartMario198, gKartMario199, gKartMario200, gKartMario201
.word gKartMario202, gKartMario203, gKartMario204, gKartMario205
.word gKartMario206, gKartMario207, gKartMario208

glabel gKartMarioGroup1
.word gKartMario021, gKartMario022, gKartMario023, gKartMario024
.word gKartMario025, gKartMario026, gKartMario027, gKartMario028
.word gKartMario029, gKartMario030, gKartMario031, gKartMario032
.word gKartMario033, gKartMario034, gKartMario035, gKartMario036
.word gKartMario037, gKartMario038, gKartMario039, gKartMario040
.word gKartMario041, gKartMario195, gKartMario196, gKartMario197
.word gKartMario198, gKartMario199, gKartMario200, gKartMario201
.word gKartMario202, gKartMario203, gKartMario204, gKartMario205
.word gKartMario206, gKartMario207, gKartMario208

glabel gKartMarioGroup2
.word gKartMario042, gKartMario043, gKartMario044, gKartMario045
.word gKartMario046, gKartMario047, gKartMario048, gKartMario049
.word gKartMario050, gKartMario051, gKartMario052, gKartMario053
.word gKartMario054, gKartMario055, gKartMario056, gKartMario057
.word gKartMario058, gKartMario059, gKartMario060, gKartMario061
.word gKartMario062, gKartMario215, gKartMario216, gKartMario217
.word gKartMario218, gKartMario219, gKartMario220, gKartMario221
.word gKartMario222, gKartMario223, gKartMario224, gKartMario225
.word gKartMario226, gKartMario227, gKartMario228

glabel gKartMarioGroup3
.word gKartMario063, gKartMario064, gKartMario065, gKartMario066
.word gKartMario067, gKartMario068, gKartMario069, gKartMario070
.word gKartMario071, gKartMario072, gKartMario073, gKartMario074
.word gKartMario075, gKartMario076, gKartMario077, gKartMario078
.word gKartMario079, gKartMario080, gKartMario081, gKartMario082
.word gKartMario083, gKartMario235, gKartMario236, gKartMario237
.word gKartMario238, gKartMario239, gKartMario240, gKartMario241
.word gKartMario242, gKartMario243, gKartMario244, gKartMario245
.word gKartMario246, gKartMario247, gKartMario248

glabel gKartMarioGroup4
.word gKartMario084, gKartMario085, gKartMario086, gKartMario087
.word gKartMario088, gKartMario089, gKartMario090, gKartMario091
.word gKartMario092, gKartMario093, gKartMario094, gKartMario095
.word gKartMario096, gKartMario097, gKartMario098, gKartMario099
.word gKartMario100, gKartMario101, gKartMario102, gKartMario103
.word gKartMario104, gKartMario235, gKartMario236, gKartMario237
.word gKartMario238, gKartMario239, gKartMario240, gKartMario241
.word gKartMario242, gKartMario243, gKartMario244, gKartMario245
.word gKartMario246, gKartMario247, gKartMario248

glabel gKartMarioGroup5
.word gKartMario105, gKartMario106, gKartMario107, gKartMario108
.word gKartMario109, gKartMario110, gKartMario111, gKartMario112
.word gKartMario113, gKartMario114, gKartMario115, gKartMario116
.word gKartMario117, gKartMario118, gKartMario119, gKartMario120
.word gKartMario121, gKartMario122, gKartMario123, gKartMario124
.word gKartMario125, gKartMario235, gKartMario236, gKartMario237
.word gKartMario238, gKartMario239, gKartMario240, gKartMario241
.word gKartMario242, gKartMario243, gKartMario244, gKartMario245
.word gKartMario246, gKartMario247, gKartMario248

glabel gKartMarioGroup6
.word gKartMario126, gKartMario127, gKartMario128, gKartMario129
.word gKartMario130, gKartMario131, gKartMario132, gKartMario133
.word gKartMario134, gKartMario135, gKartMario136, gKartMario137
.word gKartMario138, gKartMario139, gKartMario140, gKartMario141
.word gKartMario142, gKartMario143, gKartMario144, gKartMario145
.word gKartMario146, gKartMario255, gKartMario256, gKartMario257
.word gKartMario258, gKartMario259, gKartMario260, gKartMario261
.word gKartMario262, gKartMario263, gKartMario264, gKartMario265
.word gKartMario266, gKartMario267, gKartMario268

glabel gKartMarioGroup7
.word gKartMario147, gKartMario148, gKartMario149, gKartMario150
.word gKartMario151, gKartMario152, gKartMario153, gKartMario154
.word gKartMario155, gKartMario156, gKartMario157, gKartMario158
.word gKartMario159, gKartMario160, gKartMario161, gKartMario162
.word gKartMario163, gKartMario164, gKartMario165, gKartMario166
.word gKartMario167, gKartMario275, gKartMario276, gKartMario277
.word gKartMario278, gKartMario279, gKartMario280, gKartMario281
.word gKartMario282, gKartMario283, gKartMario284, gKartMario285
.word gKartMario286, gKartMario287, gKartMario288

glabel gKartMarioGroup8
.word gKartMario168, gKartMario169, gKartMario170, gKartMario171
.word gKartMario172, gKartMario173, gKartMario174, gKartMario175
.word gKartMario176, gKartMario177, gKartMario178, gKartMario179
.word gKartMario180, gKartMario181, gKartMario182, gKartMario183
.word gKartMario184, gKartMario185, gKartMario186, gKartMario187
.word gKartMario188, gKartMario275, gKartMario276, gKartMario277
.word gKartMario278, gKartMario279, gKartMario280, gKartMario281
.word gKartMario282, gKartMario283, gKartMario284, gKartMario285
.word gKartMario286, gKartMario287, gKartMario288

glabel gKartMarioGroup9
.word gKartMario189, gKartMario190, gKartMario191, gKartMario192
.word gKartMario193, gKartMario194, gKartMario195, gKartMario196
.word gKartMario197, gKartMario198, gKartMario199, gKartMario200
.word gKartMario201, gKartMario202, gKartMario203, gKartMario204
.word gKartMario205, gKartMario206, gKartMario207, gKartMario208

glabel gKartMarioGroup10
.word gKartMario189, gKartMario190, gKartMario191, gKartMario192
.word gKartMario193, gKartMario194, gKartMario195, gKartMario196
.word gKartMario197, gKartMario198, gKartMario199, gKartMario200
.word gKartMario201, gKartMario202, gKartMario203, gKartMario204
.word gKartMario205, gKartMario206, gKartMario207, gKartMario208

glabel gKartMarioGroup11
.word gKartMario209, gKartMario210, gKartMario211, gKartMario212
.word gKartMario213, gKartMario214, gKartMario215, gKartMario216
.word gKartMario217, gKartMario218, gKartMario219, gKartMario220
.word gKartMario221, gKartMario222, gKartMario223, gKartMario224
.word gKartMario225, gKartMario226, gKartMario227, gKartMario228

glabel gKartMarioGroup12
.word gKartMario229, gKartMario230, gKartMario231, gKartMario232
.word gKartMario233, gKartMario234, gKartMario235, gKartMario236
.word gKartMario237, gKartMario238, gKartMario239, gKartMario240
.word gKartMario241, gKartMario242, gKartMario243, gKartMario244
.word gKartMario245, gKartMario246, gKartMario247, gKartMario248

glabel gKartMarioGroup13
.word gKartMario229, gKartMario230, gKartMario231, gKartMario232
.word gKartMario233, gKartMario234, gKartMario235, gKartMario236
.word gKartMario237, gKartMario238, gKartMario239, gKartMario240
.word gKartMario241, gKartMario242, gKartMario243, gKartMario244
.word gKartMario245, gKartMario246, gKartMario247, gKartMario248

glabel gKartMarioGroup14
.word gKartMario229, gKartMario230, gKartMario231, gKartMario232
.word gKartMario233, gKartMario234, gKartMario235, gKartMario236
.word gKartMario237, gKartMario238, gKartMario239, gKartMario240
.word gKartMario241, gKartMario242, gKartMario243, gKartMario244
.word gKartMario245, gKartMario246, gKartMario247, gKartMario248

glabel gKartMarioGroup15
.word gKartMario249, gKartMario250, gKartMario251, gKartMario252
.word gKartMario253, gKartMario254, gKartMario255, gKartMario256
.word gKartMario257, gKartMario258, gKartMario259, gKartMario260
.word gKartMario261, gKartMario262, gKartMario263, gKartMario264
.word gKartMario265, gKartMario266, gKartMario267, gKartMario268

glabel gKartMarioGroup16
.word gKartMario269, gKartMario270, gKartMario271, gKartMario272
.word gKartMario273, gKartMario274, gKartMario275, gKartMario276
.word gKartMario277, gKartMario278, gKartMario279, gKartMario280
.word gKartMario281, gKartMario282, gKartMario283, gKartMario284
.word gKartMario285, gKartMario286, gKartMario287, gKartMario288

glabel gKartMarioGroup17
.word gKartMario269, gKartMario270, gKartMario271, gKartMario272
.word gKartMario273, gKartMario274, gKartMario275, gKartMario276
.word gKartMario277, gKartMario278, gKartMario279, gKartMario280
.word gKartMario281, gKartMario282, gKartMario283, gKartMario284
.word gKartMario285, gKartMario286, gKartMario287, gKartMario288

glabel gKartToadGroup0
.word gKartToad000, gKartToad001, gKartToad002, gKartToad003
.word gKartToad004, gKartToad005, gKartToad006, gKartToad007
.word gKartToad008, gKartToad009, gKartToad010, gKartToad011
.word gKartToad012, gKartToad013, gKartToad014, gKartToad015
.word gKartToad016, gKartToad017, gKartToad018, gKartToad019
.word gKartToad020, gKartToad195, gKartToad196, gKartToad197
.word gKartToad198, gKartToad199, gKartToad200, gKartToad201
.word gKartToad202, gKartToad203, gKartToad204, gKartToad205
.word gKartToad206, gKartToad207, gKartToad208

glabel gKartToadGroup1
.word gKartToad021, gKartToad022, gKartToad023, gKartToad024
.word gKartToad025, gKartToad026, gKartToad027, gKartToad028
.word gKartToad029, gKartToad030, gKartToad031, gKartToad032
.word gKartToad033, gKartToad034, gKartToad035, gKartToad036
.word gKartToad037, gKartToad038, gKartToad039, gKartToad040
.word gKartToad041, gKartToad195, gKartToad196, gKartToad197
.word gKartToad198, gKartToad199, gKartToad200, gKartToad201
.word gKartToad202, gKartToad203, gKartToad204, gKartToad205
.word gKartToad206, gKartToad207, gKartToad208

glabel gKartToadGroup2
.word gKartToad042, gKartToad043, gKartToad044, gKartToad045
.word gKartToad046, gKartToad047, gKartToad048, gKartToad049
.word gKartToad050, gKartToad051, gKartToad052, gKartToad053
.word gKartToad054, gKartToad055, gKartToad056, gKartToad057
.word gKartToad058, gKartToad059, gKartToad060, gKartToad061
.word gKartToad062, gKartToad215, gKartToad216, gKartToad217
.word gKartToad218, gKartToad219, gKartToad220, gKartToad221
.word gKartToad222, gKartToad223, gKartToad224, gKartToad225
.word gKartToad226, gKartToad227, gKartToad228

glabel gKartToadGroup3
.word gKartToad063, gKartToad064, gKartToad065, gKartToad066
.word gKartToad067, gKartToad068, gKartToad069, gKartToad070
.word gKartToad071, gKartToad072, gKartToad073, gKartToad074
.word gKartToad075, gKartToad076, gKartToad077, gKartToad078
.word gKartToad079, gKartToad080, gKartToad081, gKartToad082
.word gKartToad083, gKartToad235, gKartToad236, gKartToad237
.word gKartToad238, gKartToad239, gKartToad240, gKartToad241
.word gKartToad242, gKartToad243, gKartToad244, gKartToad245
.word gKartToad246, gKartToad247, gKartToad248

glabel gKartToadGroup4
.word gKartToad084, gKartToad085, gKartToad086, gKartToad087
.word gKartToad088, gKartToad089, gKartToad090, gKartToad091
.word gKartToad092, gKartToad093, gKartToad094, gKartToad095
.word gKartToad096, gKartToad097, gKartToad098, gKartToad099
.word gKartToad100, gKartToad101, gKartToad102, gKartToad103
.word gKartToad104, gKartToad235, gKartToad236, gKartToad237
.word gKartToad238, gKartToad239, gKartToad240, gKartToad241
.word gKartToad242, gKartToad243, gKartToad244, gKartToad245
.word gKartToad246, gKartToad247, gKartToad248

glabel gKartToadGroup5
.word gKartToad105, gKartToad106, gKartToad107, gKartToad108
.word gKartToad109, gKartToad110, gKartToad111, gKartToad112
.word gKartToad113, gKartToad114, gKartToad115, gKartToad116
.word gKartToad117, gKartToad118, gKartToad119, gKartToad120
.word gKartToad121, gKartToad122, gKartToad123, gKartToad124
.word gKartToad125, gKartToad235, gKartToad236, gKartToad237
.word gKartToad238, gKartToad239, gKartToad240, gKartToad241
.word gKartToad242, gKartToad243, gKartToad244, gKartToad245
.word gKartToad246, gKartToad247, gKartToad248

glabel gKartToadGroup6
.word gKartToad126, gKartToad127, gKartToad128, gKartToad129
.word gKartToad130, gKartToad131, gKartToad132, gKartToad133
.word gKartToad134, gKartToad135, gKartToad136, gKartToad137
.word gKartToad138, gKartToad139, gKartToad140, gKartToad141
.word gKartToad142, gKartToad143, gKartToad144, gKartToad145
.word gKartToad146, gKartToad255, gKartToad256, gKartToad257
.word gKartToad258, gKartToad259, gKartToad260, gKartToad261
.word gKartToad262, gKartToad263, gKartToad264, gKartToad265
.word gKartToad266, gKartToad267, gKartToad268

glabel gKartToadGroup7
.word gKartToad147, gKartToad148, gKartToad149, gKartToad150
.word gKartToad151, gKartToad152, gKartToad153, gKartToad154
.word gKartToad155, gKartToad156, gKartToad157, gKartToad158
.word gKartToad159, gKartToad160, gKartToad161, gKartToad162
.word gKartToad163, gKartToad164, gKartToad165, gKartToad166
.word gKartToad167, gKartToad275, gKartToad276, gKartToad277
.word gKartToad278, gKartToad279, gKartToad280, gKartToad281
.word gKartToad282, gKartToad283, gKartToad284, gKartToad285
.word gKartToad286, gKartToad287, gKartToad288

glabel gKartToadGroup8
.word gKartToad168, gKartToad169, gKartToad170, gKartToad171
.word gKartToad172, gKartToad173, gKartToad174, gKartToad175
.word gKartToad176, gKartToad177, gKartToad178, gKartToad179
.word gKartToad180, gKartToad181, gKartToad182, gKartToad183
.word gKartToad184, gKartToad185, gKartToad186, gKartToad187
.word gKartToad188, gKartToad275, gKartToad276, gKartToad277
.word gKartToad278, gKartToad279, gKartToad280, gKartToad281
.word gKartToad282, gKartToad283, gKartToad284, gKartToad285
.word gKartToad286, gKartToad287, gKartToad288

glabel gKartToadGroup9
.word gKartToad189, gKartToad190, gKartToad191, gKartToad192
.word gKartToad193, gKartToad194, gKartToad195, gKartToad196
.word gKartToad197, gKartToad198, gKartToad199, gKartToad200
.word gKartToad201, gKartToad202, gKartToad203, gKartToad204
.word gKartToad205, gKartToad206, gKartToad207, gKartToad208

glabel gKartToadGroup10
.word gKartToad189, gKartToad190, gKartToad191, gKartToad192
.word gKartToad193, gKartToad194, gKartToad195, gKartToad196
.word gKartToad197, gKartToad198, gKartToad199, gKartToad200
.word gKartToad201, gKartToad202, gKartToad203, gKartToad204
.word gKartToad205, gKartToad206, gKartToad207, gKartToad208

glabel gKartToadGroup11
.word gKartToad209, gKartToad210, gKartToad211, gKartToad212
.word gKartToad213, gKartToad214, gKartToad215, gKartToad216
.word gKartToad217, gKartToad218, gKartToad219, gKartToad220
.word gKartToad221, gKartToad222, gKartToad223, gKartToad224
.word gKartToad225, gKartToad226, gKartToad227, gKartToad228

glabel gKartToadGroup12
.word gKartToad229, gKartToad230, gKartToad231, gKartToad232
.word gKartToad233, gKartToad234, gKartToad235, gKartToad236
.word gKartToad237, gKartToad238, gKartToad239, gKartToad240
.word gKartToad241, gKartToad242, gKartToad243, gKartToad244
.word gKartToad245, gKartToad246, gKartToad247, gKartToad248

glabel gKartToadGroup13
.word gKartToad229, gKartToad230, gKartToad231, gKartToad232
.word gKartToad233, gKartToad234, gKartToad235, gKartToad236
.word gKartToad237, gKartToad238, gKartToad239, gKartToad240
.word gKartToad241, gKartToad242, gKartToad243, gKartToad244
.word gKartToad245, gKartToad246, gKartToad247, gKartToad248

glabel gKartToadGroup14
.word gKartToad229, gKartToad230, gKartToad231, gKartToad232
.word gKartToad233, gKartToad234, gKartToad235, gKartToad236
.word gKartToad237, gKartToad238, gKartToad239, gKartToad240
.word gKartToad241, gKartToad242, gKartToad243, gKartToad244
.word gKartToad245, gKartToad246, gKartToad247, gKartToad248

glabel gKartToadGroup15
.word gKartToad249, gKartToad250, gKartToad251, gKartToad252
.word gKartToad253, gKartToad254, gKartToad255, gKartToad256
.word gKartToad257, gKartToad258, gKartToad259, gKartToad260
.word gKartToad261, gKartToad262, gKartToad263, gKartToad264
.word gKartToad265, gKartToad266, gKartToad267, gKartToad268

glabel gKartToadGroup16
.word gKartToad269, gKartToad270, gKartToad271, gKartToad272
.word gKartToad273, gKartToad274, gKartToad275, gKartToad276
.word gKartToad277, gKartToad278, gKartToad279, gKartToad280
.word gKartToad281, gKartToad282, gKartToad283, gKartToad284
.word gKartToad285, gKartToad286, gKartToad287, gKartToad288

glabel gKartToadGroup17
.word gKartToad269, gKartToad270, gKartToad271, gKartToad272
.word gKartToad273, gKartToad274, gKartToad275, gKartToad276
.word gKartToad277, gKartToad278, gKartToad279, gKartToad280
.word gKartToad281, gKartToad282, gKartToad283, gKartToad284
.word gKartToad285, gKartToad286, gKartToad287, gKartToad288

glabel gKartLuigiGroup0
.word gKartLuigi000, gKartLuigi001, gKartLuigi002, gKartLuigi003
.word gKartLuigi004, gKartLuigi005, gKartLuigi006, gKartLuigi007
.word gKartLuigi008, gKartLuigi009, gKartLuigi010, gKartLuigi011
.word gKartLuigi012, gKartLuigi013, gKartLuigi014, gKartLuigi015
.word gKartLuigi016, gKartLuigi017, gKartLuigi018, gKartLuigi019
.word gKartLuigi020, gKartLuigi195, gKartLuigi196, gKartLuigi197
.word gKartLuigi198, gKartLuigi199, gKartLuigi200, gKartLuigi201
.word gKartLuigi202, gKartLuigi203, gKartLuigi204, gKartLuigi205
.word gKartLuigi206, gKartLuigi207, gKartLuigi208

glabel gKartLuigiGroup1
.word gKartLuigi021, gKartLuigi022, gKartLuigi023, gKartLuigi024
.word gKartLuigi025, gKartLuigi026, gKartLuigi027, gKartLuigi028
.word gKartLuigi029, gKartLuigi030, gKartLuigi031, gKartLuigi032
.word gKartLuigi033, gKartLuigi034, gKartLuigi035, gKartLuigi036
.word gKartLuigi037, gKartLuigi038, gKartLuigi039, gKartLuigi040
.word gKartLuigi041, gKartLuigi195, gKartLuigi196, gKartLuigi197
.word gKartLuigi198, gKartLuigi199, gKartLuigi200, gKartLuigi201
.word gKartLuigi202, gKartLuigi203, gKartLuigi204, gKartLuigi205
.word gKartLuigi206, gKartLuigi207, gKartLuigi208

glabel gKartLuigiGroup2
.word gKartLuigi042, gKartLuigi043, gKartLuigi044, gKartLuigi045
.word gKartLuigi046, gKartLuigi047, gKartLuigi048, gKartLuigi049
.word gKartLuigi050, gKartLuigi051, gKartLuigi052, gKartLuigi053
.word gKartLuigi054, gKartLuigi055, gKartLuigi056, gKartLuigi057
.word gKartLuigi058, gKartLuigi059, gKartLuigi060, gKartLuigi061
.word gKartLuigi062, gKartLuigi215, gKartLuigi216, gKartLuigi217
.word gKartLuigi218, gKartLuigi219, gKartLuigi220, gKartLuigi221
.word gKartLuigi222, gKartLuigi223, gKartLuigi224, gKartLuigi225
.word gKartLuigi226, gKartLuigi227, gKartLuigi228

glabel gKartLuigiGroup3
.word gKartLuigi063, gKartLuigi064, gKartLuigi065, gKartLuigi066
.word gKartLuigi067, gKartLuigi068, gKartLuigi069, gKartLuigi070
.word gKartLuigi071, gKartLuigi072, gKartLuigi073, gKartLuigi074
.word gKartLuigi075, gKartLuigi076, gKartLuigi077, gKartLuigi078
.word gKartLuigi079, gKartLuigi080, gKartLuigi081, gKartLuigi082
.word gKartLuigi083, gKartLuigi235, gKartLuigi236, gKartLuigi237
.word gKartLuigi238, gKartLuigi239, gKartLuigi240, gKartLuigi241
.word gKartLuigi242, gKartLuigi243, gKartLuigi244, gKartLuigi245
.word gKartLuigi246, gKartLuigi247, gKartLuigi248

glabel gKartLuigiGroup4
.word gKartLuigi084, gKartLuigi085, gKartLuigi086, gKartLuigi087
.word gKartLuigi088, gKartLuigi089, gKartLuigi090, gKartLuigi091
.word gKartLuigi092, gKartLuigi093, gKartLuigi094, gKartLuigi095
.word gKartLuigi096, gKartLuigi097, gKartLuigi098, gKartLuigi099
.word gKartLuigi100, gKartLuigi101, gKartLuigi102, gKartLuigi103
.word gKartLuigi104, gKartLuigi235, gKartLuigi236, gKartLuigi237
.word gKartLuigi238, gKartLuigi239, gKartLuigi240, gKartLuigi241
.word gKartLuigi242, gKartLuigi243, gKartLuigi244, gKartLuigi245
.word gKartLuigi246, gKartLuigi247, gKartLuigi248

glabel gKartLuigiGroup5
.word gKartLuigi105, gKartLuigi106, gKartLuigi107, gKartLuigi108
.word gKartLuigi109, gKartLuigi110, gKartLuigi111, gKartLuigi112
.word gKartLuigi113, gKartLuigi114, gKartLuigi115, gKartLuigi116
.word gKartLuigi117, gKartLuigi118, gKartLuigi119, gKartLuigi120
.word gKartLuigi121, gKartLuigi122, gKartLuigi123, gKartLuigi124
.word gKartLuigi125, gKartLuigi235, gKartLuigi236, gKartLuigi237
.word gKartLuigi238, gKartLuigi239, gKartLuigi240, gKartLuigi241
.word gKartLuigi242, gKartLuigi243, gKartLuigi244, gKartLuigi245
.word gKartLuigi246, gKartLuigi247, gKartLuigi248

glabel gKartLuigiGroup6
.word gKartLuigi126, gKartLuigi127, gKartLuigi128, gKartLuigi129
.word gKartLuigi130, gKartLuigi131, gKartLuigi132, gKartLuigi133
.word gKartLuigi134, gKartLuigi135, gKartLuigi136, gKartLuigi137
.word gKartLuigi138, gKartLuigi139, gKartLuigi140, gKartLuigi141
.word gKartLuigi142, gKartLuigi143, gKartLuigi144, gKartLuigi145
.word gKartLuigi146, gKartLuigi255, gKartLuigi256, gKartLuigi257
.word gKartLuigi258, gKartLuigi259, gKartLuigi260, gKartLuigi261
.word gKartLuigi262, gKartLuigi263, gKartLuigi264, gKartLuigi265
.word gKartLuigi266, gKartLuigi267, gKartLuigi268

glabel gKartLuigiGroup7
.word gKartLuigi147, gKartLuigi148, gKartLuigi149, gKartLuigi150
.word gKartLuigi151, gKartLuigi152, gKartLuigi153, gKartLuigi154
.word gKartLuigi155, gKartLuigi156, gKartLuigi157, gKartLuigi158
.word gKartLuigi159, gKartLuigi160, gKartLuigi161, gKartLuigi162
.word gKartLuigi163, gKartLuigi164, gKartLuigi165, gKartLuigi166
.word gKartLuigi167, gKartLuigi275, gKartLuigi276, gKartLuigi277
.word gKartLuigi278, gKartLuigi279, gKartLuigi280, gKartLuigi281
.word gKartLuigi282, gKartLuigi283, gKartLuigi284, gKartLuigi285
.word gKartLuigi286, gKartLuigi287, gKartLuigi288

glabel gKartLuigiGroup8
.word gKartLuigi168, gKartLuigi169, gKartLuigi170, gKartLuigi171
.word gKartLuigi172, gKartLuigi173, gKartLuigi174, gKartLuigi175
.word gKartLuigi176, gKartLuigi177, gKartLuigi178, gKartLuigi179
.word gKartLuigi180, gKartLuigi181, gKartLuigi182, gKartLuigi183
.word gKartLuigi184, gKartLuigi185, gKartLuigi186, gKartLuigi187
.word gKartLuigi188, gKartLuigi275, gKartLuigi276, gKartLuigi277
.word gKartLuigi278, gKartLuigi279, gKartLuigi280, gKartLuigi281
.word gKartLuigi282, gKartLuigi283, gKartLuigi284, gKartLuigi285
.word gKartLuigi286, gKartLuigi287, gKartLuigi288

glabel gKartLuigiGroup9
.word gKartLuigi189, gKartLuigi190, gKartLuigi191, gKartLuigi192
.word gKartLuigi193, gKartLuigi194, gKartLuigi195, gKartLuigi196
.word gKartLuigi197, gKartLuigi198, gKartLuigi199, gKartLuigi200
.word gKartLuigi201, gKartLuigi202, gKartLuigi203, gKartLuigi204
.word gKartLuigi205, gKartLuigi206, gKartLuigi207, gKartLuigi208

glabel gKartLuigiGroup10
.word gKartLuigi189, gKartLuigi190, gKartLuigi191, gKartLuigi192
.word gKartLuigi193, gKartLuigi194, gKartLuigi195, gKartLuigi196
.word gKartLuigi197, gKartLuigi198, gKartLuigi199, gKartLuigi200
.word gKartLuigi201, gKartLuigi202, gKartLuigi203, gKartLuigi204
.word gKartLuigi205, gKartLuigi206, gKartLuigi207, gKartLuigi208

glabel gKartLuigiGroup11
.word gKartLuigi209, gKartLuigi210, gKartLuigi211, gKartLuigi212
.word gKartLuigi213, gKartLuigi214, gKartLuigi215, gKartLuigi216
.word gKartLuigi217, gKartLuigi218, gKartLuigi219, gKartLuigi220
.word gKartLuigi221, gKartLuigi222, gKartLuigi223, gKartLuigi224
.word gKartLuigi225, gKartLuigi226, gKartLuigi227, gKartLuigi228

glabel gKartLuigiGroup12
.word gKartLuigi229, gKartLuigi230, gKartLuigi231, gKartLuigi232
.word gKartLuigi233, gKartLuigi234, gKartLuigi235, gKartLuigi236
.word gKartLuigi237, gKartLuigi238, gKartLuigi239, gKartLuigi240
.word gKartLuigi241, gKartLuigi242, gKartLuigi243, gKartLuigi244
.word gKartLuigi245, gKartLuigi246, gKartLuigi247, gKartLuigi248

glabel gKartLuigiGroup13
.word gKartLuigi229, gKartLuigi230, gKartLuigi231, gKartLuigi232
.word gKartLuigi233, gKartLuigi234, gKartLuigi235, gKartLuigi236
.word gKartLuigi237, gKartLuigi238, gKartLuigi239, gKartLuigi240
.word gKartLuigi241, gKartLuigi242, gKartLuigi243, gKartLuigi244
.word gKartLuigi245, gKartLuigi246, gKartLuigi247, gKartLuigi248

glabel gKartLuigiGroup14
.word gKartLuigi229, gKartLuigi230, gKartLuigi231, gKartLuigi232
.word gKartLuigi233, gKartLuigi234, gKartLuigi235, gKartLuigi236
.word gKartLuigi237, gKartLuigi238, gKartLuigi239, gKartLuigi240
.word gKartLuigi241, gKartLuigi242, gKartLuigi243, gKartLuigi244
.word gKartLuigi245, gKartLuigi246, gKartLuigi247, gKartLuigi248

glabel gKartLuigiGroup15
.word gKartLuigi249, gKartLuigi250, gKartLuigi251, gKartLuigi252
.word gKartLuigi253, gKartLuigi254, gKartLuigi255, gKartLuigi256
.word gKartLuigi257, gKartLuigi258, gKartLuigi259, gKartLuigi260
.word gKartLuigi261, gKartLuigi262, gKartLuigi263, gKartLuigi264
.word gKartLuigi265, gKartLuigi266, gKartLuigi267, gKartLuigi268

glabel gKartLuigiGroup16
.word gKartLuigi269, gKartLuigi270, gKartLuigi271, gKartLuigi272
.word gKartLuigi273, gKartLuigi274, gKartLuigi275, gKartLuigi276
.word gKartLuigi277, gKartLuigi278, gKartLuigi279, gKartLuigi280
.word gKartLuigi281, gKartLuigi282, gKartLuigi283, gKartLuigi284
.word gKartLuigi285, gKartLuigi286, gKartLuigi287, gKartLuigi288

glabel gKartLuigiGroup17
.word gKartLuigi269, gKartLuigi270, gKartLuigi271, gKartLuigi272
.word gKartLuigi273, gKartLuigi274, gKartLuigi275, gKartLuigi276
.word gKartLuigi277, gKartLuigi278, gKartLuigi279, gKartLuigi280
.word gKartLuigi281, gKartLuigi282, gKartLuigi283, gKartLuigi284
.word gKartLuigi285, gKartLuigi286, gKartLuigi287, gKartLuigi288

glabel gKartYoshiGroup0
.word gKartYoshi000, gKartYoshi001, gKartYoshi002, gKartYoshi003
.word gKartYoshi004, gKartYoshi005, gKartYoshi006, gKartYoshi007
.word gKartYoshi008, gKartYoshi009, gKartYoshi010, gKartYoshi011
.word gKartYoshi012, gKartYoshi013, gKartYoshi014, gKartYoshi015
.word gKartYoshi016, gKartYoshi017, gKartYoshi018, gKartYoshi019
.word gKartYoshi020, gKartYoshi195, gKartYoshi196, gKartYoshi197
.word gKartYoshi198, gKartYoshi199, gKartYoshi200, gKartYoshi201
.word gKartYoshi202, gKartYoshi203, gKartYoshi204, gKartYoshi205
.word gKartYoshi206, gKartYoshi207, gKartYoshi208

glabel gKartYoshiGroup1
.word gKartYoshi021, gKartYoshi022, gKartYoshi023, gKartYoshi024
.word gKartYoshi025, gKartYoshi026, gKartYoshi027, gKartYoshi028
.word gKartYoshi029, gKartYoshi030, gKartYoshi031, gKartYoshi032
.word gKartYoshi033, gKartYoshi034, gKartYoshi035, gKartYoshi036
.word gKartYoshi037, gKartYoshi038, gKartYoshi039, gKartYoshi040
.word gKartYoshi041, gKartYoshi195, gKartYoshi196, gKartYoshi197
.word gKartYoshi198, gKartYoshi199, gKartYoshi200, gKartYoshi201
.word gKartYoshi202, gKartYoshi203, gKartYoshi204, gKartYoshi205
.word gKartYoshi206, gKartYoshi207, gKartYoshi208

glabel gKartYoshiGroup2
.word gKartYoshi042, gKartYoshi043, gKartYoshi044, gKartYoshi045
.word gKartYoshi046, gKartYoshi047, gKartYoshi048, gKartYoshi049
.word gKartYoshi050, gKartYoshi051, gKartYoshi052, gKartYoshi053
.word gKartYoshi054, gKartYoshi055, gKartYoshi056, gKartYoshi057
.word gKartYoshi058, gKartYoshi059, gKartYoshi060, gKartYoshi061
.word gKartYoshi062, gKartYoshi215, gKartYoshi216, gKartYoshi217
.word gKartYoshi218, gKartYoshi219, gKartYoshi220, gKartYoshi221
.word gKartYoshi222, gKartYoshi223, gKartYoshi224, gKartYoshi225
.word gKartYoshi226, gKartYoshi227, gKartYoshi228

glabel gKartYoshiGroup3
.word gKartYoshi063, gKartYoshi064, gKartYoshi065, gKartYoshi066
.word gKartYoshi067, gKartYoshi068, gKartYoshi069, gKartYoshi070
.word gKartYoshi071, gKartYoshi072, gKartYoshi073, gKartYoshi074
.word gKartYoshi075, gKartYoshi076, gKartYoshi077, gKartYoshi078
.word gKartYoshi079, gKartYoshi080, gKartYoshi081, gKartYoshi082
.word gKartYoshi083, gKartYoshi235, gKartYoshi236, gKartYoshi237
.word gKartYoshi238, gKartYoshi239, gKartYoshi240, gKartYoshi241
.word gKartYoshi242, gKartYoshi243, gKartYoshi244, gKartYoshi245
.word gKartYoshi246, gKartYoshi247, gKartYoshi248

glabel gKartYoshiGroup4
.word gKartYoshi084, gKartYoshi085, gKartYoshi086, gKartYoshi087
.word gKartYoshi088, gKartYoshi089, gKartYoshi090, gKartYoshi091
.word gKartYoshi092, gKartYoshi093, gKartYoshi094, gKartYoshi095
.word gKartYoshi096, gKartYoshi097, gKartYoshi098, gKartYoshi099
.word gKartYoshi100, gKartYoshi101, gKartYoshi102, gKartYoshi103
.word gKartYoshi104, gKartYoshi235, gKartYoshi236, gKartYoshi237
.word gKartYoshi238, gKartYoshi239, gKartYoshi240, gKartYoshi241
.word gKartYoshi242, gKartYoshi243, gKartYoshi244, gKartYoshi245
.word gKartYoshi246, gKartYoshi247, gKartYoshi248

glabel gKartYoshiGroup5
.word gKartYoshi105, gKartYoshi106, gKartYoshi107, gKartYoshi108
.word gKartYoshi109, gKartYoshi110, gKartYoshi111, gKartYoshi112
.word gKartYoshi113, gKartYoshi114, gKartYoshi115, gKartYoshi116
.word gKartYoshi117, gKartYoshi118, gKartYoshi119, gKartYoshi120
.word gKartYoshi121, gKartYoshi122, gKartYoshi123, gKartYoshi124
.word gKartYoshi125, gKartYoshi235, gKartYoshi236, gKartYoshi237
.word gKartYoshi238, gKartYoshi239, gKartYoshi240, gKartYoshi241
.word gKartYoshi242, gKartYoshi243, gKartYoshi244, gKartYoshi245
.word gKartYoshi246, gKartYoshi247, gKartYoshi248

glabel gKartYoshiGroup6
.word gKartYoshi126, gKartYoshi127, gKartYoshi128, gKartYoshi129
.word gKartYoshi130, gKartYoshi131, gKartYoshi132, gKartYoshi133
.word gKartYoshi134, gKartYoshi135, gKartYoshi136, gKartYoshi137
.word gKartYoshi138, gKartYoshi139, gKartYoshi140, gKartYoshi141
.word gKartYoshi142, gKartYoshi143, gKartYoshi144, gKartYoshi145
.word gKartYoshi146, gKartYoshi255, gKartYoshi256, gKartYoshi257
.word gKartYoshi258, gKartYoshi259, gKartYoshi260, gKartYoshi261
.word gKartYoshi262, gKartYoshi263, gKartYoshi264, gKartYoshi265
.word gKartYoshi266, gKartYoshi267, gKartYoshi268

glabel gKartYoshiGroup7
.word gKartYoshi147, gKartYoshi148, gKartYoshi149, gKartYoshi150
.word gKartYoshi151, gKartYoshi152, gKartYoshi153, gKartYoshi154
.word gKartYoshi155, gKartYoshi156, gKartYoshi157, gKartYoshi158
.word gKartYoshi159, gKartYoshi160, gKartYoshi161, gKartYoshi162
.word gKartYoshi163, gKartYoshi164, gKartYoshi165, gKartYoshi166
.word gKartYoshi167, gKartYoshi275, gKartYoshi276, gKartYoshi277
.word gKartYoshi278, gKartYoshi279, gKartYoshi280, gKartYoshi281
.word gKartYoshi282, gKartYoshi283, gKartYoshi284, gKartYoshi285
.word gKartYoshi286, gKartYoshi287, gKartYoshi288

glabel gKartYoshiGroup8
.word gKartYoshi168, gKartYoshi169, gKartYoshi170, gKartYoshi171
.word gKartYoshi172, gKartYoshi173, gKartYoshi174, gKartYoshi175
.word gKartYoshi176, gKartYoshi177, gKartYoshi178, gKartYoshi179
.word gKartYoshi180, gKartYoshi181, gKartYoshi182, gKartYoshi183
.word gKartYoshi184, gKartYoshi185, gKartYoshi186, gKartYoshi187
.word gKartYoshi188, gKartYoshi275, gKartYoshi276, gKartYoshi277
.word gKartYoshi278, gKartYoshi279, gKartYoshi280, gKartYoshi281
.word gKartYoshi282, gKartYoshi283, gKartYoshi284, gKartYoshi285
.word gKartYoshi286, gKartYoshi287, gKartYoshi288

glabel gKartYoshiGroup9
.word gKartYoshi189, gKartYoshi190, gKartYoshi191, gKartYoshi192
.word gKartYoshi193, gKartYoshi194, gKartYoshi195, gKartYoshi196
.word gKartYoshi197, gKartYoshi198, gKartYoshi199, gKartYoshi200
.word gKartYoshi201, gKartYoshi202, gKartYoshi203, gKartYoshi204
.word gKartYoshi205, gKartYoshi206, gKartYoshi207, gKartYoshi208

glabel gKartYoshiGroup10
.word gKartYoshi189, gKartYoshi190, gKartYoshi191, gKartYoshi192
.word gKartYoshi193, gKartYoshi194, gKartYoshi195, gKartYoshi196
.word gKartYoshi197, gKartYoshi198, gKartYoshi199, gKartYoshi200
.word gKartYoshi201, gKartYoshi202, gKartYoshi203, gKartYoshi204
.word gKartYoshi205, gKartYoshi206, gKartYoshi207, gKartYoshi208

glabel gKartYoshiGroup11
.word gKartYoshi209, gKartYoshi210, gKartYoshi211, gKartYoshi212
.word gKartYoshi213, gKartYoshi214, gKartYoshi215, gKartYoshi216
.word gKartYoshi217, gKartYoshi218, gKartYoshi219, gKartYoshi220
.word gKartYoshi221, gKartYoshi222, gKartYoshi223, gKartYoshi224
.word gKartYoshi225, gKartYoshi226, gKartYoshi227, gKartYoshi228

glabel gKartYoshiGroup12
.word gKartYoshi229, gKartYoshi230, gKartYoshi231, gKartYoshi232
.word gKartYoshi233, gKartYoshi234, gKartYoshi235, gKartYoshi236
.word gKartYoshi237, gKartYoshi238, gKartYoshi239, gKartYoshi240
.word gKartYoshi241, gKartYoshi242, gKartYoshi243, gKartYoshi244
.word gKartYoshi245, gKartYoshi246, gKartYoshi247, gKartYoshi248

glabel gKartYoshiGroup13
.word gKartYoshi229, gKartYoshi230, gKartYoshi231, gKartYoshi232
.word gKartYoshi233, gKartYoshi234, gKartYoshi235, gKartYoshi236
.word gKartYoshi237, gKartYoshi238, gKartYoshi239, gKartYoshi240
.word gKartYoshi241, gKartYoshi242, gKartYoshi243, gKartYoshi244
.word gKartYoshi245, gKartYoshi246, gKartYoshi247, gKartYoshi248

glabel gKartYoshiGroup14
.word gKartYoshi229, gKartYoshi230, gKartYoshi231, gKartYoshi232
.word gKartYoshi233, gKartYoshi234, gKartYoshi235, gKartYoshi236
.word gKartYoshi237, gKartYoshi238, gKartYoshi239, gKartYoshi240
.word gKartYoshi241, gKartYoshi242, gKartYoshi243, gKartYoshi244
.word gKartYoshi245, gKartYoshi246, gKartYoshi247, gKartYoshi248

glabel gKartYoshiGroup15
.word gKartYoshi249, gKartYoshi250, gKartYoshi251, gKartYoshi252
.word gKartYoshi253, gKartYoshi254, gKartYoshi255, gKartYoshi256
.word gKartYoshi257, gKartYoshi258, gKartYoshi259, gKartYoshi260
.word gKartYoshi261, gKartYoshi262, gKartYoshi263, gKartYoshi264
.word gKartYoshi265, gKartYoshi266, gKartYoshi267, gKartYoshi268

glabel gKartYoshiGroup16
.word gKartYoshi269, gKartYoshi270, gKartYoshi271, gKartYoshi272
.word gKartYoshi273, gKartYoshi274, gKartYoshi275, gKartYoshi276
.word gKartYoshi277, gKartYoshi278, gKartYoshi279, gKartYoshi280
.word gKartYoshi281, gKartYoshi282, gKartYoshi283, gKartYoshi284
.word gKartYoshi285, gKartYoshi286, gKartYoshi287, gKartYoshi288

glabel gKartYoshiGroup17
.word gKartYoshi269, gKartYoshi270, gKartYoshi271, gKartYoshi272
.word gKartYoshi273, gKartYoshi274, gKartYoshi275, gKartYoshi276
.word gKartYoshi277, gKartYoshi278, gKartYoshi279, gKartYoshi280
.word gKartYoshi281, gKartYoshi282, gKartYoshi283, gKartYoshi284
.word gKartYoshi285, gKartYoshi286, gKartYoshi287, gKartYoshi288

glabel gKartDKGroup0
.word gKartDK000, gKartDK001, gKartDK002, gKartDK003
.word gKartDK004, gKartDK005, gKartDK006, gKartDK007
.word gKartDK008, gKartDK009, gKartDK010, gKartDK011
.word gKartDK012, gKartDK013, gKartDK014, gKartDK015
.word gKartDK016, gKartDK017, gKartDK018, gKartDK019
.word gKartDK020, gKartDK195, gKartDK196, gKartDK197
.word gKartDK198, gKartDK199, gKartDK200, gKartDK201
.word gKartDK202, gKartDK203, gKartDK204, gKartDK205
.word gKartDK206, gKartDK207, gKartDK208

glabel gKartDKGroup1
.word gKartDK021, gKartDK022, gKartDK023, gKartDK024
.word gKartDK025, gKartDK026, gKartDK027, gKartDK028
.word gKartDK029, gKartDK030, gKartDK031, gKartDK032
.word gKartDK033, gKartDK034, gKartDK035, gKartDK036
.word gKartDK037, gKartDK038, gKartDK039, gKartDK040
.word gKartDK041, gKartDK195, gKartDK196, gKartDK197
.word gKartDK198, gKartDK199, gKartDK200, gKartDK201
.word gKartDK202, gKartDK203, gKartDK204, gKartDK205
.word gKartDK206, gKartDK207, gKartDK208

glabel gKartDKGroup2
.word gKartDK042, gKartDK043, gKartDK044, gKartDK045
.word gKartDK046, gKartDK047, gKartDK048, gKartDK049
.word gKartDK050, gKartDK051, gKartDK052, gKartDK053
.word gKartDK054, gKartDK055, gKartDK056, gKartDK057
.word gKartDK058, gKartDK059, gKartDK060, gKartDK061
.word gKartDK062, gKartDK215, gKartDK216, gKartDK217
.word gKartDK218, gKartDK219, gKartDK220, gKartDK221
.word gKartDK222, gKartDK223, gKartDK224, gKartDK225
.word gKartDK226, gKartDK227, gKartDK228

glabel gKartDKGroup3
.word gKartDK063, gKartDK064, gKartDK065, gKartDK066
.word gKartDK067, gKartDK068, gKartDK069, gKartDK070
.word gKartDK071, gKartDK072, gKartDK073, gKartDK074
.word gKartDK075, gKartDK076, gKartDK077, gKartDK078
.word gKartDK079, gKartDK080, gKartDK081, gKartDK082
.word gKartDK083, gKartDK235, gKartDK236, gKartDK237
.word gKartDK238, gKartDK239, gKartDK240, gKartDK241
.word gKartDK242, gKartDK243, gKartDK244, gKartDK245
.word gKartDK246, gKartDK247, gKartDK248

glabel gKartDKGroup4
.word gKartDK084, gKartDK085, gKartDK086, gKartDK087
.word gKartDK088, gKartDK089, gKartDK090, gKartDK091
.word gKartDK092, gKartDK093, gKartDK094, gKartDK095
.word gKartDK096, gKartDK097, gKartDK098, gKartDK099
.word gKartDK100, gKartDK101, gKartDK102, gKartDK103
.word gKartDK104, gKartDK235, gKartDK236, gKartDK237
.word gKartDK238, gKartDK239, gKartDK240, gKartDK241
.word gKartDK242, gKartDK243, gKartDK244, gKartDK245
.word gKartDK246, gKartDK247, gKartDK248

glabel gKartDKGroup5
.word gKartDK105, gKartDK106, gKartDK107, gKartDK108
.word gKartDK109, gKartDK110, gKartDK111, gKartDK112
.word gKartDK113, gKartDK114, gKartDK115, gKartDK116
.word gKartDK117, gKartDK118, gKartDK119, gKartDK120
.word gKartDK121, gKartDK122, gKartDK123, gKartDK124
.word gKartDK125, gKartDK235, gKartDK236, gKartDK237
.word gKartDK238, gKartDK239, gKartDK240, gKartDK241
.word gKartDK242, gKartDK243, gKartDK244, gKartDK245
.word gKartDK246, gKartDK247, gKartDK248

glabel gKartDKGroup6
.word gKartDK126, gKartDK127, gKartDK128, gKartDK129
.word gKartDK130, gKartDK131, gKartDK132, gKartDK133
.word gKartDK134, gKartDK135, gKartDK136, gKartDK137
.word gKartDK138, gKartDK139, gKartDK140, gKartDK141
.word gKartDK142, gKartDK143, gKartDK144, gKartDK145
.word gKartDK146, gKartDK255, gKartDK256, gKartDK257
.word gKartDK258, gKartDK259, gKartDK260, gKartDK261
.word gKartDK262, gKartDK263, gKartDK264, gKartDK265
.word gKartDK266, gKartDK267, gKartDK268

glabel gKartDKGroup7
.word gKartDK147, gKartDK148, gKartDK149, gKartDK150
.word gKartDK151, gKartDK152, gKartDK153, gKartDK154
.word gKartDK155, gKartDK156, gKartDK157, gKartDK158
.word gKartDK159, gKartDK160, gKartDK161, gKartDK162
.word gKartDK163, gKartDK164, gKartDK165, gKartDK166
.word gKartDK167, gKartDK275, gKartDK276, gKartDK277
.word gKartDK278, gKartDK279, gKartDK280, gKartDK281
.word gKartDK282, gKartDK283, gKartDK284, gKartDK285
.word gKartDK286, gKartDK287, gKartDK288

glabel gKartDKGroup8
.word gKartDK168, gKartDK169, gKartDK170, gKartDK171
.word gKartDK172, gKartDK173, gKartDK174, gKartDK175
.word gKartDK176, gKartDK177, gKartDK178, gKartDK179
.word gKartDK180, gKartDK181, gKartDK182, gKartDK183
.word gKartDK184, gKartDK185, gKartDK186, gKartDK187
.word gKartDK188, gKartDK275, gKartDK276, gKartDK277
.word gKartDK278, gKartDK279, gKartDK280, gKartDK281
.word gKartDK282, gKartDK283, gKartDK284, gKartDK285
.word gKartDK286, gKartDK287, gKartDK288

glabel gKartDKGroup9
.word gKartDK189, gKartDK190, gKartDK191, gKartDK192
.word gKartDK193, gKartDK194, gKartDK195, gKartDK196
.word gKartDK197, gKartDK198, gKartDK199, gKartDK200
.word gKartDK201, gKartDK202, gKartDK203, gKartDK204
.word gKartDK205, gKartDK206, gKartDK207, gKartDK208

glabel gKartDKGroup10
.word gKartDK189, gKartDK190, gKartDK191, gKartDK192
.word gKartDK193, gKartDK194, gKartDK195, gKartDK196
.word gKartDK197, gKartDK198, gKartDK199, gKartDK200
.word gKartDK201, gKartDK202, gKartDK203, gKartDK204
.word gKartDK205, gKartDK206, gKartDK207, gKartDK208

glabel gKartDKGroup11
.word gKartDK209, gKartDK210, gKartDK211, gKartDK212
.word gKartDK213, gKartDK214, gKartDK215, gKartDK216
.word gKartDK217, gKartDK218, gKartDK219, gKartDK220
.word gKartDK221, gKartDK222, gKartDK223, gKartDK224
.word gKartDK225, gKartDK226, gKartDK227, gKartDK228

glabel gKartDKGroup12
.word gKartDK229, gKartDK230, gKartDK231, gKartDK232
.word gKartDK233, gKartDK234, gKartDK235, gKartDK236
.word gKartDK237, gKartDK238, gKartDK239, gKartDK240
.word gKartDK241, gKartDK242, gKartDK243, gKartDK244
.word gKartDK245, gKartDK246, gKartDK247, gKartDK248

glabel gKartDKGroup13
.word gKartDK229, gKartDK230, gKartDK231, gKartDK232
.word gKartDK233, gKartDK234, gKartDK235, gKartDK236
.word gKartDK237, gKartDK238, gKartDK239, gKartDK240
.word gKartDK241, gKartDK242, gKartDK243, gKartDK244
.word gKartDK245, gKartDK246, gKartDK247, gKartDK248

glabel gKartDKGroup14
.word gKartDK229, gKartDK230, gKartDK231, gKartDK232
.word gKartDK233, gKartDK234, gKartDK235, gKartDK236
.word gKartDK237, gKartDK238, gKartDK239, gKartDK240
.word gKartDK241, gKartDK242, gKartDK243, gKartDK244
.word gKartDK245, gKartDK246, gKartDK247, gKartDK248

glabel gKartDKGroup15
.word gKartDK249, gKartDK250, gKartDK251, gKartDK252
.word gKartDK253, gKartDK254, gKartDK255, gKartDK256
.word gKartDK257, gKartDK258, gKartDK259, gKartDK260
.word gKartDK261, gKartDK262, gKartDK263, gKartDK264
.word gKartDK265, gKartDK266, gKartDK267, gKartDK268

glabel gKartDKGroup16
.word gKartDK269, gKartDK270, gKartDK271, gKartDK272
.word gKartDK273, gKartDK274, gKartDK275, gKartDK276
.word gKartDK277, gKartDK278, gKartDK279, gKartDK280
.word gKartDK281, gKartDK282, gKartDK283, gKartDK284
.word gKartDK285, gKartDK286, gKartDK287, gKartDK288

glabel gKartDKGroup17
.word gKartDK269, gKartDK270, gKartDK271, gKartDK272
.word gKartDK273, gKartDK274, gKartDK275, gKartDK276
.word gKartDK277, gKartDK278, gKartDK279, gKartDK280
.word gKartDK281, gKartDK282, gKartDK283, gKartDK284
.word gKartDK285, gKartDK286, gKartDK287, gKartDK288

glabel gKartBowserGroup0
.word gKartBowser000, gKartBowser001, gKartBowser002, gKartBowser003
.word gKartBowser004, gKartBowser005, gKartBowser006, gKartBowser007
.word gKartBowser008, gKartBowser009, gKartBowser010, gKartBowser011
.word gKartBowser012, gKartBowser013, gKartBowser014, gKartBowser015
.word gKartBowser016, gKartBowser017, gKartBowser018, gKartBowser019
.word gKartBowser020, gKartBowser195, gKartBowser196, gKartBowser197
.word gKartBowser198, gKartBowser199, gKartBowser200, gKartBowser201
.word gKartBowser202, gKartBowser203, gKartBowser204, gKartBowser205
.word gKartBowser206, gKartBowser207, gKartBowser208

glabel gKartBowserGroup1
.word gKartBowser021, gKartBowser022, gKartBowser023, gKartBowser024
.word gKartBowser025, gKartBowser026, gKartBowser027, gKartBowser028
.word gKartBowser029, gKartBowser030, gKartBowser031, gKartBowser032
.word gKartBowser033, gKartBowser034, gKartBowser035, gKartBowser036
.word gKartBowser037, gKartBowser038, gKartBowser039, gKartBowser040
.word gKartBowser041, gKartBowser195, gKartBowser196, gKartBowser197
.word gKartBowser198, gKartBowser199, gKartBowser200, gKartBowser201
.word gKartBowser202, gKartBowser203, gKartBowser204, gKartBowser205
.word gKartBowser206, gKartBowser207, gKartBowser208

glabel gKartBowserGroup2
.word gKartBowser042, gKartBowser043, gKartBowser044, gKartBowser045
.word gKartBowser046, gKartBowser047, gKartBowser048, gKartBowser049
.word gKartBowser050, gKartBowser051, gKartBowser052, gKartBowser053
.word gKartBowser054, gKartBowser055, gKartBowser056, gKartBowser057
.word gKartBowser058, gKartBowser059, gKartBowser060, gKartBowser061
.word gKartBowser062, gKartBowser215, gKartBowser216, gKartBowser217
.word gKartBowser218, gKartBowser219, gKartBowser220, gKartBowser221
.word gKartBowser222, gKartBowser223, gKartBowser224, gKartBowser225
.word gKartBowser226, gKartBowser227, gKartBowser228

glabel gKartBowserGroup3
.word gKartBowser063, gKartBowser064, gKartBowser065, gKartBowser066
.word gKartBowser067, gKartBowser068, gKartBowser069, gKartBowser070
.word gKartBowser071, gKartBowser072, gKartBowser073, gKartBowser074
.word gKartBowser075, gKartBowser076, gKartBowser077, gKartBowser078
.word gKartBowser079, gKartBowser080, gKartBowser081, gKartBowser082
.word gKartBowser083, gKartBowser235, gKartBowser236, gKartBowser237
.word gKartBowser238, gKartBowser239, gKartBowser240, gKartBowser241
.word gKartBowser242, gKartBowser243, gKartBowser244, gKartBowser245
.word gKartBowser246, gKartBowser247, gKartBowser248

glabel gKartBowserGroup4
.word gKartBowser084, gKartBowser085, gKartBowser086, gKartBowser087
.word gKartBowser088, gKartBowser089, gKartBowser090, gKartBowser091
.word gKartBowser092, gKartBowser093, gKartBowser094, gKartBowser095
.word gKartBowser096, gKartBowser097, gKartBowser098, gKartBowser099
.word gKartBowser100, gKartBowser101, gKartBowser102, gKartBowser103
.word gKartBowser104, gKartBowser235, gKartBowser236, gKartBowser237
.word gKartBowser238, gKartBowser239, gKartBowser240, gKartBowser241
.word gKartBowser242, gKartBowser243, gKartBowser244, gKartBowser245
.word gKartBowser246, gKartBowser247, gKartBowser248

glabel gKartBowserGroup5
.word gKartBowser105, gKartBowser106, gKartBowser107, gKartBowser108
.word gKartBowser109, gKartBowser110, gKartBowser111, gKartBowser112
.word gKartBowser113, gKartBowser114, gKartBowser115, gKartBowser116
.word gKartBowser117, gKartBowser118, gKartBowser119, gKartBowser120
.word gKartBowser121, gKartBowser122, gKartBowser123, gKartBowser124
.word gKartBowser125, gKartBowser235, gKartBowser236, gKartBowser237
.word gKartBowser238, gKartBowser239, gKartBowser240, gKartBowser241
.word gKartBowser242, gKartBowser243, gKartBowser244, gKartBowser245
.word gKartBowser246, gKartBowser247, gKartBowser248

glabel gKartBowserGroup6
.word gKartBowser126, gKartBowser127, gKartBowser128, gKartBowser129
.word gKartBowser130, gKartBowser131, gKartBowser132, gKartBowser133
.word gKartBowser134, gKartBowser135, gKartBowser136, gKartBowser137
.word gKartBowser138, gKartBowser139, gKartBowser140, gKartBowser141
.word gKartBowser142, gKartBowser143, gKartBowser144, gKartBowser145
.word gKartBowser146, gKartBowser255, gKartBowser256, gKartBowser257
.word gKartBowser258, gKartBowser259, gKartBowser260, gKartBowser261
.word gKartBowser262, gKartBowser263, gKartBowser264, gKartBowser265
.word gKartBowser266, gKartBowser267, gKartBowser268

glabel gKartBowserGroup7
.word gKartBowser147, gKartBowser148, gKartBowser149, gKartBowser150
.word gKartBowser151, gKartBowser152, gKartBowser153, gKartBowser154
.word gKartBowser155, gKartBowser156, gKartBowser157, gKartBowser158
.word gKartBowser159, gKartBowser160, gKartBowser161, gKartBowser162
.word gKartBowser163, gKartBowser164, gKartBowser165, gKartBowser166
.word gKartBowser167, gKartBowser275, gKartBowser276, gKartBowser277
.word gKartBowser278, gKartBowser279, gKartBowser280, gKartBowser281
.word gKartBowser282, gKartBowser283, gKartBowser284, gKartBowser285
.word gKartBowser286, gKartBowser287, gKartBowser288

glabel gKartBowserGroup8
.word gKartBowser168, gKartBowser169, gKartBowser170, gKartBowser171
.word gKartBowser172, gKartBowser173, gKartBowser174, gKartBowser175
.word gKartBowser176, gKartBowser177, gKartBowser178, gKartBowser179
.word gKartBowser180, gKartBowser181, gKartBowser182, gKartBowser183
.word gKartBowser184, gKartBowser185, gKartBowser186, gKartBowser187
.word gKartBowser188, gKartBowser275, gKartBowser276, gKartBowser277
.word gKartBowser278, gKartBowser279, gKartBowser280, gKartBowser281
.word gKartBowser282, gKartBowser283, gKartBowser284, gKartBowser285
.word gKartBowser286, gKartBowser287, gKartBowser288

glabel gKartBowserGroup9
.word gKartBowser189, gKartBowser190, gKartBowser191, gKartBowser192
.word gKartBowser193, gKartBowser194, gKartBowser195, gKartBowser196
.word gKartBowser197, gKartBowser198, gKartBowser199, gKartBowser200
.word gKartBowser201, gKartBowser202, gKartBowser203, gKartBowser204
.word gKartBowser205, gKartBowser206, gKartBowser207, gKartBowser208

glabel gKartBowserGroup10
.word gKartBowser189, gKartBowser190, gKartBowser191, gKartBowser192
.word gKartBowser193, gKartBowser194, gKartBowser195, gKartBowser196
.word gKartBowser197, gKartBowser198, gKartBowser199, gKartBowser200
.word gKartBowser201, gKartBowser202, gKartBowser203, gKartBowser204
.word gKartBowser205, gKartBowser206, gKartBowser207, gKartBowser208

glabel gKartBowserGroup11
.word gKartBowser209, gKartBowser210, gKartBowser211, gKartBowser212
.word gKartBowser213, gKartBowser214, gKartBowser215, gKartBowser216
.word gKartBowser217, gKartBowser218, gKartBowser219, gKartBowser220
.word gKartBowser221, gKartBowser222, gKartBowser223, gKartBowser224
.word gKartBowser225, gKartBowser226, gKartBowser227, gKartBowser228

glabel gKartBowserGroup12
.word gKartBowser229, gKartBowser230, gKartBowser231, gKartBowser232
.word gKartBowser233, gKartBowser234, gKartBowser235, gKartBowser236
.word gKartBowser237, gKartBowser238, gKartBowser239, gKartBowser240
.word gKartBowser241, gKartBowser242, gKartBowser243, gKartBowser244
.word gKartBowser245, gKartBowser246, gKartBowser247, gKartBowser248

glabel gKartBowserGroup13
.word gKartBowser229, gKartBowser230, gKartBowser231, gKartBowser232
.word gKartBowser233, gKartBowser234, gKartBowser235, gKartBowser236
.word gKartBowser237, gKartBowser238, gKartBowser239, gKartBowser240
.word gKartBowser241, gKartBowser242, gKartBowser243, gKartBowser244
.word gKartBowser245, gKartBowser246, gKartBowser247, gKartBowser248

glabel gKartBowserGroup14
.word gKartBowser229, gKartBowser230, gKartBowser231, gKartBowser232
.word gKartBowser233, gKartBowser234, gKartBowser235, gKartBowser236
.word gKartBowser237, gKartBowser238, gKartBowser239, gKartBowser240
.word gKartBowser241, gKartBowser242, gKartBowser243, gKartBowser244
.word gKartBowser245, gKartBowser246, gKartBowser247, gKartBowser248

glabel gKartBowserGroup15
.word gKartBowser249, gKartBowser250, gKartBowser251, gKartBowser252
.word gKartBowser253, gKartBowser254, gKartBowser255, gKartBowser256
.word gKartBowser257, gKartBowser258, gKartBowser259, gKartBowser260
.word gKartBowser261, gKartBowser262, gKartBowser263, gKartBowser264
.word gKartBowser265, gKartBowser266, gKartBowser267, gKartBowser268

glabel gKartBowserGroup16
.word gKartBowser269, gKartBowser270, gKartBowser271, gKartBowser272
.word gKartBowser273, gKartBowser274, gKartBowser275, gKartBowser276
.word gKartBowser277, gKartBowser278, gKartBowser279, gKartBowser280
.word gKartBowser281, gKartBowser282, gKartBowser283, gKartBowser284
.word gKartBowser285, gKartBowser286, gKartBowser287, gKartBowser288

glabel gKartBowserGroup17
.word gKartBowser269, gKartBowser270, gKartBowser271, gKartBowser272
.word gKartBowser273, gKartBowser274, gKartBowser275, gKartBowser276
.word gKartBowser277, gKartBowser278, gKartBowser279, gKartBowser280
.word gKartBowser281, gKartBowser282, gKartBowser283, gKartBowser284
.word gKartBowser285, gKartBowser286, gKartBowser287, gKartBowser288

glabel gKartPeachGroup0
.word gKartPeach000, gKartPeach001, gKartPeach002, gKartPeach003
.word gKartPeach004, gKartPeach005, gKartPeach006, gKartPeach007
.word gKartPeach008, gKartPeach009, gKartPeach010, gKartPeach011
.word gKartPeach012, gKartPeach013, gKartPeach014, gKartPeach015
.word gKartPeach016, gKartPeach017, gKartPeach018, gKartPeach019
.word gKartPeach020, gKartPeach195, gKartPeach196, gKartPeach197
.word gKartPeach198, gKartPeach199, gKartPeach200, gKartPeach201
.word gKartPeach202, gKartPeach203, gKartPeach204, gKartPeach205
.word gKartPeach206, gKartPeach207, gKartPeach208

glabel gKartPeachGroup1
.word gKartPeach021, gKartPeach022, gKartPeach023, gKartPeach024
.word gKartPeach025, gKartPeach026, gKartPeach027, gKartPeach028
.word gKartPeach029, gKartPeach030, gKartPeach031, gKartPeach032
.word gKartPeach033, gKartPeach034, gKartPeach035, gKartPeach036
.word gKartPeach037, gKartPeach038, gKartPeach039, gKartPeach040
.word gKartPeach041, gKartPeach195, gKartPeach196, gKartPeach197
.word gKartPeach198, gKartPeach199, gKartPeach200, gKartPeach201
.word gKartPeach202, gKartPeach203, gKartPeach204, gKartPeach205
.word gKartPeach206, gKartPeach207, gKartPeach208

glabel gKartPeachGroup2
.word gKartPeach042, gKartPeach043, gKartPeach044, gKartPeach045
.word gKartPeach046, gKartPeach047, gKartPeach048, gKartPeach049
.word gKartPeach050, gKartPeach051, gKartPeach052, gKartPeach053
.word gKartPeach054, gKartPeach055, gKartPeach056, gKartPeach057
.word gKartPeach058, gKartPeach059, gKartPeach060, gKartPeach061
.word gKartPeach062, gKartPeach215, gKartPeach216, gKartPeach217
.word gKartPeach218, gKartPeach219, gKartPeach220, gKartPeach221
.word gKartPeach222, gKartPeach223, gKartPeach224, gKartPeach225
.word gKartPeach226, gKartPeach227, gKartPeach228

glabel gKartPeachGroup3
.word gKartPeach063, gKartPeach064, gKartPeach065, gKartPeach066
.word gKartPeach067, gKartPeach068, gKartPeach069, gKartPeach070
.word gKartPeach071, gKartPeach072, gKartPeach073, gKartPeach074
.word gKartPeach075, gKartPeach076, gKartPeach077, gKartPeach078
.word gKartPeach079, gKartPeach080, gKartPeach081, gKartPeach082
.word gKartPeach083, gKartPeach235, gKartPeach236, gKartPeach237
.word gKartPeach238, gKartPeach239, gKartPeach240, gKartPeach241
.word gKartPeach242, gKartPeach243, gKartPeach244, gKartPeach245
.word gKartPeach246, gKartPeach247, gKartPeach248

glabel gKartPeachGroup4
.word gKartPeach084, gKartPeach085, gKartPeach086, gKartPeach087
.word gKartPeach088, gKartPeach089, gKartPeach090, gKartPeach091
.word gKartPeach092, gKartPeach093, gKartPeach094, gKartPeach095
.word gKartPeach096, gKartPeach097, gKartPeach098, gKartPeach099
.word gKartPeach100, gKartPeach101, gKartPeach102, gKartPeach103
.word gKartPeach104, gKartPeach235, gKartPeach236, gKartPeach237
.word gKartPeach238, gKartPeach239, gKartPeach240, gKartPeach241
.word gKartPeach242, gKartPeach243, gKartPeach244, gKartPeach245
.word gKartPeach246, gKartPeach247, gKartPeach248

glabel gKartPeachGroup5
.word gKartPeach105, gKartPeach106, gKartPeach107, gKartPeach108
.word gKartPeach109, gKartPeach110, gKartPeach111, gKartPeach112
.word gKartPeach113, gKartPeach114, gKartPeach115, gKartPeach116
.word gKartPeach117, gKartPeach118, gKartPeach119, gKartPeach120
.word gKartPeach121, gKartPeach122, gKartPeach123, gKartPeach124
.word gKartPeach125, gKartPeach235, gKartPeach236, gKartPeach237
.word gKartPeach238, gKartPeach239, gKartPeach240, gKartPeach241
.word gKartPeach242, gKartPeach243, gKartPeach244, gKartPeach245
.word gKartPeach246, gKartPeach247, gKartPeach248

glabel gKartPeachGroup6
.word gKartPeach126, gKartPeach127, gKartPeach128, gKartPeach129
.word gKartPeach130, gKartPeach131, gKartPeach132, gKartPeach133
.word gKartPeach134, gKartPeach135, gKartPeach136, gKartPeach137
.word gKartPeach138, gKartPeach139, gKartPeach140, gKartPeach141
.word gKartPeach142, gKartPeach143, gKartPeach144, gKartPeach145
.word gKartPeach146, gKartPeach255, gKartPeach256, gKartPeach257
.word gKartPeach258, gKartPeach259, gKartPeach260, gKartPeach261
.word gKartPeach262, gKartPeach263, gKartPeach264, gKartPeach265
.word gKartPeach266, gKartPeach267, gKartPeach268

glabel gKartPeachGroup7
.word gKartPeach147, gKartPeach148, gKartPeach149, gKartPeach150
.word gKartPeach151, gKartPeach152, gKartPeach153, gKartPeach154
.word gKartPeach155, gKartPeach156, gKartPeach157, gKartPeach158
.word gKartPeach159, gKartPeach160, gKartPeach161, gKartPeach162
.word gKartPeach163, gKartPeach164, gKartPeach165, gKartPeach166
.word gKartPeach167, gKartPeach275, gKartPeach276, gKartPeach277
.word gKartPeach278, gKartPeach279, gKartPeach280, gKartPeach281
.word gKartPeach282, gKartPeach283, gKartPeach284, gKartPeach285
.word gKartPeach286, gKartPeach287, gKartPeach288

glabel gKartPeachGroup8
.word gKartPeach168, gKartPeach169, gKartPeach170, gKartPeach171
.word gKartPeach172, gKartPeach173, gKartPeach174, gKartPeach175
.word gKartPeach176, gKartPeach177, gKartPeach178, gKartPeach179
.word gKartPeach180, gKartPeach181, gKartPeach182, gKartPeach183
.word gKartPeach184, gKartPeach185, gKartPeach186, gKartPeach187
.word gKartPeach188, gKartPeach275, gKartPeach276, gKartPeach277
.word gKartPeach278, gKartPeach279, gKartPeach280, gKartPeach281
.word gKartPeach282, gKartPeach283, gKartPeach284, gKartPeach285
.word gKartPeach286, gKartPeach287, gKartPeach288

glabel gKartPeachGroup9
.word gKartPeach189, gKartPeach190, gKartPeach191, gKartPeach192
.word gKartPeach193, gKartPeach194, gKartPeach195, gKartPeach196
.word gKartPeach197, gKartPeach198, gKartPeach199, gKartPeach200
.word gKartPeach201, gKartPeach202, gKartPeach203, gKartPeach204
.word gKartPeach205, gKartPeach206, gKartPeach207, gKartPeach208

glabel gKartPeachGroup10
.word gKartPeach189, gKartPeach190, gKartPeach191, gKartPeach192
.word gKartPeach193, gKartPeach194, gKartPeach195, gKartPeach196
.word gKartPeach197, gKartPeach198, gKartPeach199, gKartPeach200
.word gKartPeach201, gKartPeach202, gKartPeach203, gKartPeach204
.word gKartPeach205, gKartPeach206, gKartPeach207, gKartPeach208

glabel gKartPeachGroup11
.word gKartPeach209, gKartPeach210, gKartPeach211, gKartPeach212
.word gKartPeach213, gKartPeach214, gKartPeach215, gKartPeach216
.word gKartPeach217, gKartPeach218, gKartPeach219, gKartPeach220
.word gKartPeach221, gKartPeach222, gKartPeach223, gKartPeach224
.word gKartPeach225, gKartPeach226, gKartPeach227, gKartPeach228

glabel gKartPeachGroup12
.word gKartPeach229, gKartPeach230, gKartPeach231, gKartPeach232
.word gKartPeach233, gKartPeach234, gKartPeach235, gKartPeach236
.word gKartPeach237, gKartPeach238, gKartPeach239, gKartPeach240
.word gKartPeach241, gKartPeach242, gKartPeach243, gKartPeach244
.word gKartPeach245, gKartPeach246, gKartPeach247, gKartPeach248

glabel gKartPeachGroup13
.word gKartPeach229, gKartPeach230, gKartPeach231, gKartPeach232
.word gKartPeach233, gKartPeach234, gKartPeach235, gKartPeach236
.word gKartPeach237, gKartPeach238, gKartPeach239, gKartPeach240
.word gKartPeach241, gKartPeach242, gKartPeach243, gKartPeach244
.word gKartPeach245, gKartPeach246, gKartPeach247, gKartPeach248

glabel gKartPeachGroup14
.word gKartPeach229, gKartPeach230, gKartPeach231, gKartPeach232
.word gKartPeach233, gKartPeach234, gKartPeach235, gKartPeach236
.word gKartPeach237, gKartPeach238, gKartPeach239, gKartPeach240
.word gKartPeach241, gKartPeach242, gKartPeach243, gKartPeach244
.word gKartPeach245, gKartPeach246, gKartPeach247, gKartPeach248

glabel gKartPeachGroup15
.word gKartPeach249, gKartPeach250, gKartPeach251, gKartPeach252
.word gKartPeach253, gKartPeach254, gKartPeach255, gKartPeach256
.word gKartPeach257, gKartPeach258, gKartPeach259, gKartPeach260
.word gKartPeach261, gKartPeach262, gKartPeach263, gKartPeach264
.word gKartPeach265, gKartPeach266, gKartPeach267, gKartPeach268

glabel gKartPeachGroup16
.word gKartPeach269, gKartPeach270, gKartPeach271, gKartPeach272
.word gKartPeach273, gKartPeach274, gKartPeach275, gKartPeach276
.word gKartPeach277, gKartPeach278, gKartPeach279, gKartPeach280
.word gKartPeach281, gKartPeach282, gKartPeach283, gKartPeach284
.word gKartPeach285, gKartPeach286, gKartPeach287, gKartPeach288

glabel gKartPeachGroup17
.word gKartPeach269, gKartPeach270, gKartPeach271, gKartPeach272
.word gKartPeach273, gKartPeach274, gKartPeach275, gKartPeach276
.word gKartPeach277, gKartPeach278, gKartPeach279, gKartPeach280
.word gKartPeach281, gKartPeach282, gKartPeach283, gKartPeach284
.word gKartPeach285, gKartPeach286, gKartPeach287, gKartPeach288

glabel gKartWarioGroup0
.word gKartWario000, gKartWario001, gKartWario002, gKartWario003
.word gKartWario004, gKartWario005, gKartWario006, gKartWario007
.word gKartWario008, gKartWario009, gKartWario010, gKartWario011
.word gKartWario012, gKartWario013, gKartWario014, gKartWario015
.word gKartWario016, gKartWario017, gKartWario018, gKartWario019
.word gKartWario020, gKartWario195, gKartWario196, gKartWario197
.word gKartWario198, gKartWario199, gKartWario200, gKartWario201
.word gKartWario202, gKartWario203, gKartWario204, gKartWario205
.word gKartWario206, gKartWario207, gKartWario208

glabel gKartWarioGroup1
.word gKartWario021, gKartWario022, gKartWario023, gKartWario024
.word gKartWario025, gKartWario026, gKartWario027, gKartWario028
.word gKartWario029, gKartWario030, gKartWario031, gKartWario032
.word gKartWario033, gKartWario034, gKartWario035, gKartWario036
.word gKartWario037, gKartWario038, gKartWario039, gKartWario040
.word gKartWario041, gKartWario195, gKartWario196, gKartWario197
.word gKartWario198, gKartWario199, gKartWario200, gKartWario201
.word gKartWario202, gKartWario203, gKartWario204, gKartWario205
.word gKartWario206, gKartWario207, gKartWario208

glabel gKartWarioGroup2
.word gKartWario042, gKartWario043, gKartWario044, gKartWario045
.word gKartWario046, gKartWario047, gKartWario048, gKartWario049
.word gKartWario050, gKartWario051, gKartWario052, gKartWario053
.word gKartWario054, gKartWario055, gKartWario056, gKartWario057
.word gKartWario058, gKartWario059, gKartWario060, gKartWario061
.word gKartWario062, gKartWario215, gKartWario216, gKartWario217
.word gKartWario218, gKartWario219, gKartWario220, gKartWario221
.word gKartWario222, gKartWario223, gKartWario224, gKartWario225
.word gKartWario226, gKartWario227, gKartWario228

glabel gKartWarioGroup3
.word gKartWario063, gKartWario064, gKartWario065, gKartWario066
.word gKartWario067, gKartWario068, gKartWario069, gKartWario070
.word gKartWario071, gKartWario072, gKartWario073, gKartWario074
.word gKartWario075, gKartWario076, gKartWario077, gKartWario078
.word gKartWario079, gKartWario080, gKartWario081, gKartWario082
.word gKartWario083, gKartWario235, gKartWario236, gKartWario237
.word gKartWario238, gKartWario239, gKartWario240, gKartWario241
.word gKartWario242, gKartWario243, gKartWario244, gKartWario245
.word gKartWario246, gKartWario247, gKartWario248

glabel gKartWarioGroup4
.word gKartWario084, gKartWario085, gKartWario086, gKartWario087
.word gKartWario088, gKartWario089, gKartWario090, gKartWario091
.word gKartWario092, gKartWario093, gKartWario094, gKartWario095
.word gKartWario096, gKartWario097, gKartWario098, gKartWario099
.word gKartWario100, gKartWario101, gKartWario102, gKartWario103
.word gKartWario104, gKartWario235, gKartWario236, gKartWario237
.word gKartWario238, gKartWario239, gKartWario240, gKartWario241
.word gKartWario242, gKartWario243, gKartWario244, gKartWario245
.word gKartWario246, gKartWario247, gKartWario248

glabel gKartWarioGroup5
.word gKartWario105, gKartWario106, gKartWario107, gKartWario108
.word gKartWario109, gKartWario110, gKartWario111, gKartWario112
.word gKartWario113, gKartWario114, gKartWario115, gKartWario116
.word gKartWario117, gKartWario118, gKartWario119, gKartWario120
.word gKartWario121, gKartWario122, gKartWario123, gKartWario124
.word gKartWario125, gKartWario235, gKartWario236, gKartWario237
.word gKartWario238, gKartWario239, gKartWario240, gKartWario241
.word gKartWario242, gKartWario243, gKartWario244, gKartWario245
.word gKartWario246, gKartWario247, gKartWario248

glabel gKartWarioGroup6
.word gKartWario126, gKartWario127, gKartWario128, gKartWario129
.word gKartWario130, gKartWario131, gKartWario132, gKartWario133
.word gKartWario134, gKartWario135, gKartWario136, gKartWario137
.word gKartWario138, gKartWario139, gKartWario140, gKartWario141
.word gKartWario142, gKartWario143, gKartWario144, gKartWario145
.word gKartWario146, gKartWario255, gKartWario256, gKartWario257
.word gKartWario258, gKartWario259, gKartWario260, gKartWario261
.word gKartWario262, gKartWario263, gKartWario264, gKartWario265
.word gKartWario266, gKartWario267, gKartWario268

glabel gKartWarioGroup7
.word gKartWario147, gKartWario148, gKartWario149, gKartWario150
.word gKartWario151, gKartWario152, gKartWario153, gKartWario154
.word gKartWario155, gKartWario156, gKartWario157, gKartWario158
.word gKartWario159, gKartWario160, gKartWario161, gKartWario162
.word gKartWario163, gKartWario164, gKartWario165, gKartWario166
.word gKartWario167, gKartWario275, gKartWario276, gKartWario277
.word gKartWario278, gKartWario279, gKartWario280, gKartWario281
.word gKartWario282, gKartWario283, gKartWario284, gKartWario285
.word gKartWario286, gKartWario287, gKartWario288

glabel gKartWarioGroup8
.word gKartWario168, gKartWario169, gKartWario170, gKartWario171
.word gKartWario172, gKartWario173, gKartWario174, gKartWario175
.word gKartWario176, gKartWario177, gKartWario178, gKartWario179
.word gKartWario180, gKartWario181, gKartWario182, gKartWario183
.word gKartWario184, gKartWario185, gKartWario186, gKartWario187
.word gKartWario188, gKartWario275, gKartWario276, gKartWario277
.word gKartWario278, gKartWario279, gKartWario280, gKartWario281
.word gKartWario282, gKartWario283, gKartWario284, gKartWario285
.word gKartWario286, gKartWario287, gKartWario288

glabel gKartWarioGroup9
.word gKartWario189, gKartWario190, gKartWario191, gKartWario192
.word gKartWario193, gKartWario194, gKartWario195, gKartWario196
.word gKartWario197, gKartWario198, gKartWario199, gKartWario200
.word gKartWario201, gKartWario202, gKartWario203, gKartWario204
.word gKartWario205, gKartWario206, gKartWario207, gKartWario208

glabel gKartWarioGroup10
.word gKartWario189, gKartWario190, gKartWario191, gKartWario192
.word gKartWario193, gKartWario194, gKartWario195, gKartWario196
.word gKartWario197, gKartWario198, gKartWario199, gKartWario200
.word gKartWario201, gKartWario202, gKartWario203, gKartWario204
.word gKartWario205, gKartWario206, gKartWario207, gKartWario208

glabel gKartWarioGroup11
.word gKartWario209, gKartWario210, gKartWario211, gKartWario212
.word gKartWario213, gKartWario214, gKartWario215, gKartWario216
.word gKartWario217, gKartWario218, gKartWario219, gKartWario220
.word gKartWario221, gKartWario222, gKartWario223, gKartWario224
.word gKartWario225, gKartWario226, gKartWario227, gKartWario228

glabel gKartWarioGroup12
.word gKartWario229, gKartWario230, gKartWario231, gKartWario232
.word gKartWario233, gKartWario234, gKartWario235, gKartWario236
.word gKartWario237, gKartWario238, gKartWario239, gKartWario240
.word gKartWario241, gKartWario242, gKartWario243, gKartWario244
.word gKartWario245, gKartWario246, gKartWario247, gKartWario248

glabel gKartWarioGroup13
.word gKartWario229, gKartWario230, gKartWario231, gKartWario232
.word gKartWario233, gKartWario234, gKartWario235, gKartWario236
.word gKartWario237, gKartWario238, gKartWario239, gKartWario240
.word gKartWario241, gKartWario242, gKartWario243, gKartWario244
.word gKartWario245, gKartWario246, gKartWario247, gKartWario248

glabel gKartWarioGroup14
.word gKartWario229, gKartWario230, gKartWario231, gKartWario232
.word gKartWario233, gKartWario234, gKartWario235, gKartWario236
.word gKartWario237, gKartWario238, gKartWario239, gKartWario240
.word gKartWario241, gKartWario242, gKartWario243, gKartWario244
.word gKartWario245, gKartWario246, gKartWario247, gKartWario248

glabel gKartWarioGroup15
.word gKartWario249, gKartWario250, gKartWario251, gKartWario252
.word gKartWario253, gKartWario254, gKartWario255, gKartWario256
.word gKartWario257, gKartWario258, gKartWario259, gKartWario260
.word gKartWario261, gKartWario262, gKartWario263, gKartWario264
.word gKartWario265, gKartWario266, gKartWario267, gKartWario268

glabel gKartWarioGroup16
.word gKartWario269, gKartWario270, gKartWario271, gKartWario272
.word gKartWario273, gKartWario274, gKartWario275, gKartWario276
.word gKartWario277, gKartWario278, gKartWario279, gKartWario280
.word gKartWario281, gKartWario282, gKartWario283, gKartWario284
.word gKartWario285, gKartWario286, gKartWario287, gKartWario288

glabel gKartWarioGroup17
.word gKartWario269, gKartWario270, gKartWario271, gKartWario272
.word gKartWario273, gKartWario274, gKartWario275, gKartWario276
.word gKartWario277, gKartWario278, gKartWario279, gKartWario280
.word gKartWario281, gKartWario282, gKartWario283, gKartWario284
.word gKartWario285, gKartWario286, gKartWario287, gKartWario288

#glabel gKartMarioTable0
#.word gKartMarioGroup8, gKartMarioGroup7, gKartMarioGroup6, gKartMarioGroup5
#.word gKartMarioGroup4, gKartMarioGroup3, gKartMarioGroup2, gKartMarioGroup1
#.word gKartMarioGroup0

#glabel gKartLuigiTable0
#.word gKartLuigiGroup8, gKartLuigiGroup7, gKartLuigiGroup6, gKartLuigiGroup5
#.word gKartLuigiGroup4, gKartLuigiGroup3, gKartLuigiGroup2, gKartLuigiGroup1
#.word gKartLuigiGroup0

#glabel gKartYoshiTable0
#.word gKartYoshiGroup8, gKartYoshiGroup7, gKartYoshiGroup6, gKartYoshiGroup5
#.word gKartYoshiGroup4, gKartYoshiGroup3, gKartYoshiGroup2, gKartYoshiGroup1
#.word gKartYoshiGroup0

#glabel gKartToadTable0
#.word gKartToadGroup8, gKartToadGroup7, gKartToadGroup6, gKartToadGroup5
#.word gKartToadGroup4, gKartToadGroup3, gKartToadGroup2, gKartToadGroup1
#.word gKartToadGroup0

#glabel gKartDKTable0
#.word gKartDKGroup8, gKartDKGroup7, gKartDKGroup6, gKartDKGroup5
#.word gKartDKGroup4, gKartDKGroup3, gKartDKGroup2, gKartDKGroup1
#.word gKartDKGroup0

#glabel gKartWarioTable0
#.word gKartWarioGroup8, gKartWarioGroup7, gKartWarioGroup6, gKartWarioGroup5
#.word gKartWarioGroup4, gKartWarioGroup3, gKartWarioGroup2, gKartWarioGroup1
#.word gKartWarioGroup0

#glabel gKartPeachTable0
#.word gKartPeachGroup8, gKartPeachGroup7, gKartPeachGroup6, gKartPeachGroup5
#.word gKartPeachGroup4, gKartPeachGroup3, gKartPeachGroup2, gKartPeachGroup1
#.word gKartPeachGroup0

#glabel gKartBowserTable0
#.word gKartBowserGroup8, gKartBowserGroup7, gKartBowserGroup6, gKartBowserGroup5
#.word gKartBowserGroup4, gKartBowserGroup3, gKartBowserGroup2, gKartBowserGroup1
#.word gKartBowserGroup0

#glabel gKartMarioTable1
#.word gKartMarioGroup17, gKartMarioGroup16, gKartMarioGroup15, gKartMarioGroup14
#.word gKartMarioGroup13, gKartMarioGroup12, gKartMarioGroup11, gKartMarioGroup10
#.word gKartMarioGroup9

#glabel gKartLuigiTable1
#.word gKartLuigiGroup17, gKartLuigiGroup16, gKartLuigiGroup15, gKartLuigiGroup14
#.word gKartLuigiGroup13, gKartLuigiGroup12, gKartLuigiGroup11, gKartLuigiGroup10
#.word gKartLuigiGroup9

#glabel gKartYoshiTable1
#.word gKartYoshiGroup17, gKartYoshiGroup16, gKartYoshiGroup15, gKartYoshiGroup14
#.word gKartYoshiGroup13, gKartYoshiGroup12, gKartYoshiGroup11, gKartYoshiGroup10
#.word gKartYoshiGroup9

#glabel gKartToadTable1
#.word gKartToadGroup17, gKartToadGroup16, gKartToadGroup15, gKartToadGroup14
#.word gKartToadGroup13, gKartToadGroup12, gKartToadGroup11, gKartToadGroup10
#.word gKartToadGroup9

#glabel gKartDKTable1
#.word gKartDKGroup17, gKartDKGroup16, gKartDKGroup15, gKartDKGroup14
#.word gKartDKGroup13, gKartDKGroup12, gKartDKGroup11, gKartDKGroup10
#.word gKartDKGroup9

#glabel gKartWarioTable1
#.word gKartWarioGroup17, gKartWarioGroup16, gKartWarioGroup15, gKartWarioGroup14
#.word gKartWarioGroup13, gKartWarioGroup12, gKartWarioGroup11, gKartWarioGroup10
#.word gKartWarioGroup9

#glabel gKartPeachTable1
#.word gKartPeachGroup17, gKartPeachGroup16, gKartPeachGroup15, gKartPeachGroup14
#.word gKartPeachGroup13, gKartPeachGroup12, gKartPeachGroup11, gKartPeachGroup10
#.word gKartPeachGroup9

#glabel gKartBowserTable1
#.word gKartBowserGroup17, gKartBowserGroup16, gKartBowserGroup15, gKartBowserGroup14
#.word gKartBowserGroup13, gKartBowserGroup12, gKartBowserGroup11, gKartBowserGroup10
#.word gKartBowserGroup9

#glabel gKartTextureTable0
#.word gKartMarioTable0
#.word gKartLuigiTable0
#.word gKartYoshiTable0
#.word gKartToadTable0
#.word gKartDKTable0
#.word gKartWarioTable0
#.word gKartPeachTable0
#.word gKartBowserTable0

#glabel gKartTextureTable1
#.word gKartMarioTable1
#.word gKartLuigiTable1
#.word gKartYoshiTable1
#.word gKartToadTable1
#.word gKartDKTable1
#.word gKartWarioTable1
#.word gKartPeachTable1
#.word gKartBowserTable1
