MARIO_KART_DIR := assets/karts/mario

MARIO_KART_FRAME_PNG := \
 $(MARIO_KART_DIR)/frames/mario_kart_frame000.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame001.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame002.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame003.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame004.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame005.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame006.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame007.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame008.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame009.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame010.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame011.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame012.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame013.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame014.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame015.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame016.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame017.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame018.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame019.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame020.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame021.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame022.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame023.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame024.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame025.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame026.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame027.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame028.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame029.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame030.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame031.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame032.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame033.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame034.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame035.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame036.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame037.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame038.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame039.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame040.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame041.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame042.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame043.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame044.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame045.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame046.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame047.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame048.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame049.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame050.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame051.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame052.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame053.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame054.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame055.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame056.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame057.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame058.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame059.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame060.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame061.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame062.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame063.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame064.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame065.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame066.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame067.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame068.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame069.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame070.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame071.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame072.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame073.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame074.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame075.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame076.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame077.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame078.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame079.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame080.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame081.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame082.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame083.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame084.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame085.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame086.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame087.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame088.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame089.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame090.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame091.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame092.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame093.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame094.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame095.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame096.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame097.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame098.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame099.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame100.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame101.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame102.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame103.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame104.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame105.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame106.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame107.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame108.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame109.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame110.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame111.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame112.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame113.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame114.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame115.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame116.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame117.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame118.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame119.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame120.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame121.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame122.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame123.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame124.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame125.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame126.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame127.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame128.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame129.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame130.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame131.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame132.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame133.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame134.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame135.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame136.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame137.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame138.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame139.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame140.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame141.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame142.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame143.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame144.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame145.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame146.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame147.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame148.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame149.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame150.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame151.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame152.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame153.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame154.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame155.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame156.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame157.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame158.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame159.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame160.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame161.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame162.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame163.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame164.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame165.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame166.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame167.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame168.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame169.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame170.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame171.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame172.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame173.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame174.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame175.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame176.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame177.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame178.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame179.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame180.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame181.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame182.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame183.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame184.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame185.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame186.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame187.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame188.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame189.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame190.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame191.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame192.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame193.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame194.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame195.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame196.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame197.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame198.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame199.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame200.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame201.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame202.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame203.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame204.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame205.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame206.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame207.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame208.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame209.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame210.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame211.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame212.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame213.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame214.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame215.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame216.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame217.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame218.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame219.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame220.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame221.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame222.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame223.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame224.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame225.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame226.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame227.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame228.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame229.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame230.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame231.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame232.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame233.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame234.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame235.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame236.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame237.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame238.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame239.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame240.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame241.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame242.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame243.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame244.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame245.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame246.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame247.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame248.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame249.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame250.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame251.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame252.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame253.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame254.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame255.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame256.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame257.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame258.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame259.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame260.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame261.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame262.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame263.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame264.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame265.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame266.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame267.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame268.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame269.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame270.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame271.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame272.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame273.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame274.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame275.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame276.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame277.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame278.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame279.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame280.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame281.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame282.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame283.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame284.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame285.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame286.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame287.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame288.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame289.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame290.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame291.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame292.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame293.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame294.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame295.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame296.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame297.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame298.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame299.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame300.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame301.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame302.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame303.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame304.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame305.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame306.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame307.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame308.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame309.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame310.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame311.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame312.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame313.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame314.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame315.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame316.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame317.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame318.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame319.png \
 $(MARIO_KART_DIR)/frames/mario_kart_frame320.png

MARIO_KART_PALETTE_PNG := \
 $(MARIO_KART_DIR)/palettes/kart_000_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_000_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_000_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_000_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_001_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_001_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_001_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_001_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_002_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_002_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_002_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_002_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_003_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_003_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_003_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_003_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_004_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_004_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_004_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_004_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_005_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_005_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_005_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_005_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_006_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_006_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_006_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_006_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_007_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_007_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_007_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_007_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_008_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_008_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_008_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_008_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_009_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_009_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_009_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_009_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_010_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_010_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_010_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_010_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_011_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_011_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_011_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_011_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_012_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_012_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_012_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_012_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_013_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_013_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_013_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_013_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_014_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_014_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_014_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_014_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_015_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_015_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_015_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_015_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_016_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_016_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_016_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_016_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_017_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_017_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_017_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_017_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_018_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_018_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_018_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_018_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_019_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_019_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_019_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_019_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_020_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_020_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_020_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_020_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_021_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_021_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_021_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_021_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_022_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_022_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_022_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_022_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_023_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_023_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_023_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_023_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_024_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_024_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_024_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_024_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_025_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_025_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_025_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_025_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_026_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_026_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_026_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_026_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_027_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_027_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_027_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_027_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_028_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_028_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_028_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_028_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_029_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_029_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_029_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_029_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_030_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_030_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_030_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_030_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_031_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_031_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_031_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_031_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_032_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_032_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_032_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_032_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_033_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_033_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_033_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_033_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_034_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_034_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_034_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_034_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_035_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_035_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_035_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_035_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_036_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_036_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_036_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_036_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_037_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_037_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_037_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_037_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_038_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_038_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_038_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_038_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_039_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_039_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_039_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_039_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_040_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_040_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_040_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_040_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_041_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_041_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_041_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_041_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_042_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_042_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_042_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_042_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_043_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_043_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_043_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_043_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_044_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_044_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_044_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_044_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_045_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_045_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_045_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_045_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_046_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_046_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_046_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_046_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_047_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_047_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_047_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_047_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_048_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_048_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_048_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_048_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_049_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_049_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_049_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_049_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_050_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_050_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_050_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_050_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_051_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_051_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_051_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_051_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_052_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_052_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_052_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_052_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_053_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_053_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_053_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_053_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_054_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_054_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_054_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_054_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_055_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_055_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_055_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_055_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_056_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_056_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_056_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_056_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_057_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_057_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_057_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_057_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_058_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_058_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_058_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_058_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_059_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_059_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_059_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_059_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_060_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_060_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_060_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_060_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_061_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_061_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_061_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_061_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_062_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_062_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_062_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_062_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_063_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_063_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_063_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_063_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_064_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_064_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_064_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_064_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_065_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_065_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_065_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_065_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_066_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_066_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_066_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_066_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_067_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_067_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_067_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_067_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_068_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_068_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_068_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_068_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_069_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_069_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_069_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_069_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_070_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_070_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_070_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_070_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_071_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_071_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_071_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_071_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_072_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_072_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_072_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_072_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_073_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_073_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_073_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_073_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_074_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_074_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_074_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_074_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_075_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_075_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_075_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_075_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_076_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_076_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_076_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_076_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_077_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_077_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_077_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_077_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_078_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_078_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_078_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_078_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_079_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_079_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_079_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_079_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_080_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_080_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_080_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_080_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_081_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_081_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_081_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_081_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_082_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_082_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_082_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_082_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_083_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_083_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_083_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_083_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_084_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_084_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_084_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_084_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_085_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_085_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_085_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_085_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_086_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_086_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_086_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_086_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_087_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_087_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_087_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_087_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_088_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_088_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_088_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_088_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_089_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_089_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_089_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_089_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_090_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_090_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_090_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_090_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_091_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_091_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_091_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_091_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_092_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_092_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_092_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_092_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_093_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_093_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_093_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_093_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_094_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_094_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_094_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_094_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_095_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_095_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_095_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_095_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_096_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_096_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_096_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_096_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_097_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_097_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_097_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_097_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_098_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_098_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_098_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_098_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_099_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_099_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_099_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_099_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_100_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_100_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_100_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_100_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_101_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_101_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_101_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_101_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_102_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_102_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_102_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_102_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_103_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_103_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_103_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_103_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_104_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_104_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_104_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_104_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_105_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_105_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_105_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_105_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_106_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_106_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_106_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_106_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_107_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_107_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_107_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_107_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_108_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_108_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_108_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_108_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_109_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_109_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_109_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_109_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_110_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_110_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_110_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_110_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_111_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_111_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_111_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_111_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_112_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_112_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_112_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_112_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_113_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_113_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_113_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_113_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_114_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_114_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_114_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_114_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_115_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_115_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_115_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_115_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_116_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_116_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_116_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_116_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_117_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_117_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_117_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_117_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_118_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_118_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_118_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_118_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_119_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_119_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_119_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_119_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_120_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_120_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_120_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_120_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_121_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_121_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_121_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_121_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_122_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_122_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_122_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_122_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_123_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_123_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_123_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_123_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_124_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_124_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_124_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_124_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_125_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_125_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_125_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_125_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_126_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_126_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_126_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_126_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_127_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_127_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_127_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_127_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_128_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_128_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_128_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_128_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_129_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_129_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_129_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_129_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_130_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_130_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_130_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_130_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_131_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_131_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_131_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_131_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_132_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_132_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_132_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_132_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_133_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_133_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_133_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_133_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_134_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_134_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_134_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_134_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_135_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_135_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_135_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_135_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_136_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_136_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_136_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_136_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_137_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_137_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_137_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_137_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_138_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_138_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_138_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_138_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_139_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_139_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_139_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_139_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_140_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_140_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_140_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_140_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_141_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_141_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_141_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_141_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_142_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_142_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_142_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_142_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_143_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_143_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_143_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_143_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_144_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_144_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_144_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_144_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_145_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_145_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_145_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_145_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_146_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_146_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_146_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_146_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_147_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_147_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_147_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_147_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_148_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_148_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_148_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_148_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_149_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_149_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_149_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_149_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_150_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_150_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_150_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_150_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_151_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_151_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_151_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_151_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_152_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_152_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_152_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_152_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_153_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_153_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_153_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_153_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_154_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_154_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_154_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_154_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_155_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_155_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_155_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_155_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_156_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_156_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_156_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_156_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_157_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_157_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_157_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_157_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_158_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_158_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_158_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_158_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_159_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_159_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_159_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_159_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_160_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_160_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_160_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_160_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_161_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_161_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_161_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_161_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_162_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_162_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_162_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_162_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_163_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_163_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_163_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_163_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_164_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_164_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_164_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_164_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_165_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_165_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_165_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_165_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_166_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_166_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_166_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_166_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_167_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_167_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_167_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_167_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_168_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_168_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_168_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_168_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_169_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_169_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_169_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_169_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_170_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_170_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_170_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_170_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_171_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_171_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_171_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_171_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_172_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_172_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_172_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_172_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_173_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_173_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_173_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_173_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_174_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_174_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_174_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_174_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_175_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_175_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_175_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_175_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_176_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_176_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_176_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_176_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_177_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_177_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_177_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_177_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_178_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_178_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_178_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_178_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_179_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_179_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_179_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_179_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_180_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_180_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_180_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_180_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_181_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_181_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_181_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_181_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_182_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_182_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_182_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_182_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_183_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_183_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_183_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_183_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_184_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_184_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_184_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_184_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_185_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_185_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_185_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_185_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_186_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_186_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_186_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_186_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_187_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_187_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_187_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_187_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_188_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_188_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_188_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_188_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_189_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_189_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_189_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_189_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_190_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_190_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_190_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_190_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_191_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_191_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_191_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_191_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_192_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_192_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_192_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_192_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_193_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_193_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_193_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_193_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_194_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_194_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_194_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_194_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_195_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_195_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_195_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_195_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_196_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_196_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_196_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_196_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_197_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_197_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_197_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_197_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_198_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_198_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_198_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_198_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_199_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_199_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_199_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_199_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_200_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_200_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_200_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_200_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_201_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_201_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_201_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_201_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_202_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_202_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_202_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_202_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_203_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_203_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_203_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_203_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_204_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_204_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_204_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_204_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_205_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_205_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_205_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_205_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_206_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_206_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_206_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_206_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_207_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_207_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_207_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_207_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_208_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_208_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_208_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_208_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_209_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_209_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_209_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_209_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_210_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_210_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_210_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_210_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_211_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_211_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_211_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_211_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_212_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_212_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_212_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_212_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_213_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_213_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_213_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_213_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_214_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_214_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_214_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_214_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_215_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_215_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_215_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_215_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_216_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_216_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_216_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_216_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_217_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_217_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_217_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_217_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_218_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_218_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_218_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_218_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_219_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_219_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_219_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_219_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_220_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_220_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_220_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_220_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_221_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_221_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_221_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_221_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_222_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_222_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_222_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_222_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_223_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_223_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_223_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_223_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_224_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_224_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_224_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_224_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_225_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_225_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_225_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_225_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_226_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_226_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_226_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_226_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_227_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_227_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_227_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_227_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_228_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_228_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_228_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_228_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_229_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_229_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_229_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_229_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_230_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_230_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_230_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_230_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_231_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_231_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_231_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_231_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_232_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_232_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_232_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_232_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_233_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_233_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_233_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_233_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_234_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_234_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_234_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_234_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_235_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_235_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_235_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_235_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_236_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_236_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_236_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_236_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_237_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_237_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_237_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_237_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_238_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_238_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_238_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_238_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_239_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_239_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_239_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_239_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_240_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_240_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_240_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_240_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_241_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_241_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_241_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_241_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_242_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_242_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_242_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_242_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_243_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_243_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_243_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_243_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_244_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_244_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_244_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_244_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_245_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_245_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_245_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_245_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_246_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_246_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_246_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_246_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_247_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_247_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_247_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_247_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_248_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_248_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_248_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_248_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_249_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_249_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_249_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_249_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_250_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_250_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_250_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_250_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_251_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_251_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_251_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_251_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_252_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_252_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_252_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_252_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_253_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_253_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_253_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_253_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_254_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_254_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_254_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_254_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_255_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_255_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_255_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_255_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_256_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_256_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_256_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_256_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_257_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_257_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_257_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_257_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_258_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_258_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_258_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_258_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_259_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_259_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_259_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_259_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_260_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_260_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_260_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_260_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_261_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_261_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_261_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_261_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_262_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_262_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_262_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_262_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_263_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_263_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_263_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_263_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_264_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_264_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_264_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_264_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_265_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_265_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_265_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_265_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_266_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_266_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_266_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_266_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_267_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_267_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_267_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_267_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_268_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_268_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_268_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_268_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_269_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_269_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_269_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_269_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_270_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_270_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_270_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_270_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_271_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_271_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_271_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_271_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_272_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_272_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_272_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_272_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_273_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_273_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_273_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_273_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_274_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_274_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_274_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_274_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_275_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_275_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_275_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_275_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_276_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_276_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_276_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_276_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_277_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_277_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_277_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_277_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_278_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_278_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_278_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_278_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_279_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_279_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_279_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_279_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_280_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_280_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_280_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_280_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_281_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_281_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_281_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_281_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_282_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_282_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_282_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_282_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_283_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_283_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_283_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_283_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_284_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_284_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_284_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_284_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_285_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_285_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_285_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_285_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_286_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_286_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_286_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_286_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_287_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_287_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_287_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_287_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/kart_288_wheel_0.png \
 $(MARIO_KART_DIR)/palettes/kart_288_wheel_1.png \
 $(MARIO_KART_DIR)/palettes/kart_288_wheel_2.png \
 $(MARIO_KART_DIR)/palettes/kart_288_wheel_3.png \
 $(MARIO_KART_DIR)/palettes/mario_kart_palette.png

MARIO_EXPORT_SENTINEL := $(MARIO_KART_DIR)/.export

ASSET_DIRECTORIES += $(MARIO_KART_DIR)

$(BUILD_DIR)/$(DATA_DIR)/karts/mario_kart.o: $(MARIO_KART_FRAME_PNG:%.png=%.mio0) $(MARIO_KART_PALETTE_PNG:%.png=%.bin)

$(MARIO_KART_FRAME_PNG:%.png=%.mio0): %.mio0 : %.bin
	$(MIO0TOOL) -c $< $@

$(MARIO_KART_FRAME_PNG:%.png=%.bin): %.bin : %.png
	$(N64GRAPHICS) -Z $@ -g $< -s raw -f ci8 -c rgba16 -p $(<D)/stitched_palettes/$(<F:%.png=%_stitched_palette.png) -M $(<D)/wheel_masks/$(<F:%.png=%_wheel_mask.raw)

$(MARIO_KART_PALETTE_PNG:%.png=%.bin): %.bin : %.png
	$(N64GRAPHICS) -i $@ -g $< -s raw -f rgba16

$(MARIO_KART_FRAME_PNG) $(MARIO_KART_PALETTE_PNG): $(MARIO_EXPORT_SENTINEL) ;

$(MARIO_EXPORT_SENTINEL): $(ASSET_DIR)/karts/mario_kart.json
	$(ASSET_EXTRACT) $(BASEROM) $<
	touch $@
